#!/usr/bin/env python3
"""Batch 11: Final push to ~1000 sections.
Fills remaining gaps across specialties and adds granular sub-topics.
Target: ~160 new sections (843 → ~1003).
"""

import hashlib
import json
import os


def _id(guideline: str, title: str) -> str:
    raw = f"{guideline}|{title}"
    h = hashlib.md5(raw.encode()).hexdigest()[:8]
    return f"bb-{h}"


# (guideline, society, year, title, text, grade, strength, conditions, meds, measurements, keywords)
SECTIONS = [
    # ── Cardiology – deeper sub-topics ────────────────────────────────
    (
        "ACC/AHA Hypertrophic Cardiomyopathy",
        "ACC/AHA", 2024,
        "HCM Medical Therapy",
        "Beta-blockers or non-dihydropyridine calcium channel blockers are first-line for symptomatic obstructive HCM. Mavacamten may be considered for patients with refractory symptoms despite standard therapy.",
        "B", "Strong",
        ["hypertrophic cardiomyopathy", "lvot obstruction"],
        ["metoprolol", "verapamil", "mavacamten", "disopyramide"],
        ["lvot gradient", "ejection fraction"],
        ["hcm", "hypertrophic cardiomyopathy", "obstructive", "mavacamten"],
    ),
    (
        "ACC/AHA Hypertrophic Cardiomyopathy",
        "ACC/AHA", 2024,
        "HCM SCD Risk Stratification",
        "ICD implantation is recommended for HCM patients with prior cardiac arrest or sustained ventricular tachycardia. Risk stratification should incorporate family history, unexplained syncope, LV wall thickness ≥30 mm, nonsustained VT, and abnormal BP response to exercise.",
        "B", "Strong",
        ["hypertrophic cardiomyopathy", "sudden cardiac death"],
        [],
        ["lv wall thickness", "holter monitor"],
        ["hcm", "icd", "sudden death", "risk stratification"],
    ),
    (
        "ACC/AHA Pericarditis",
        "ACC/AHA", 2024,
        "Acute Pericarditis Initial Treatment",
        "Colchicine combined with NSAIDs or aspirin is recommended as first-line therapy for acute pericarditis. Duration of colchicine is typically 3 months. Corticosteroids should be avoided as first-line therapy due to risk of recurrence.",
        "A", "Strong",
        ["acute pericarditis", "chest pain"],
        ["colchicine", "ibuprofen", "aspirin", "indomethacin"],
        ["crp", "esr", "echocardiogram"],
        ["pericarditis", "colchicine", "nsaid", "recurrent"],
    ),
    (
        "ACC/AHA Infective Endocarditis Prevention",
        "ACC/AHA", 2024,
        "IE Prophylaxis – High-Risk Patients",
        "Antibiotic prophylaxis before dental procedures is recommended only for patients at highest risk: prosthetic heart valves, prior endocarditis, unrepaired cyanotic CHD, or cardiac transplant with valvulopathy. Amoxicillin 2 g PO 30-60 minutes before procedure is standard.",
        "B", "Strong",
        ["infective endocarditis", "dental procedure"],
        ["amoxicillin", "clindamycin", "azithromycin"],
        [],
        ["endocarditis", "prophylaxis", "dental", "prosthetic valve"],
    ),
    (
        "HRS Supraventricular Tachycardia",
        "HRS", 2024,
        "SVT Acute Management",
        "Vagal maneuvers are first-line for acute termination of SVT. If ineffective, IV adenosine (6 mg rapid push, may repeat 12 mg) is recommended. For hemodynamically unstable SVT, synchronized cardioversion is indicated.",
        "A", "Strong",
        ["supraventricular tachycardia", "avnrt", "avrt"],
        ["adenosine", "verapamil", "diltiazem"],
        ["12-lead ecg", "heart rate"],
        ["svt", "adenosine", "cardioversion", "tachycardia"],
    ),
    (
        "ACC/AHA Stable Angina",
        "ACC/AHA", 2024,
        "Stable Angina Anti-Ischemic Therapy",
        "Beta-blockers or calcium channel blockers are first-line anti-ischemic therapy for stable angina. Sublingual nitroglycerin for acute symptom relief. Ranolazine may be added as second-line for persistent symptoms.",
        "A", "Strong",
        ["stable angina", "chronic coronary disease"],
        ["metoprolol", "amlodipine", "nitroglycerin", "ranolazine"],
        ["stress test", "coronary cta"],
        ["stable angina", "anti-ischemic", "beta blocker", "ccb"],
    ),
    (
        "ACC/AHA PFO Closure",
        "ACC/AHA", 2024,
        "PFO Closure After Cryptogenic Stroke",
        "PFO closure may be considered for patients aged 18-60 with cryptogenic stroke and PFO with high-risk features (atrial septal aneurysm, large shunt). Antiplatelet therapy alone is an alternative. Shared decision-making is essential.",
        "B", "Moderate",
        ["patent foramen ovale", "cryptogenic stroke"],
        ["aspirin", "clopidogrel"],
        ["bubble study", "tee"],
        ["pfo", "cryptogenic stroke", "closure device"],
    ),
    # ── Pulmonology – additional topics ───────────────────────────────
    (
        "ATS/ERS Sarcoidosis",
        "ATS/ERS", 2024,
        "Pulmonary Sarcoidosis Treatment",
        "Systemic corticosteroids are first-line for symptomatic pulmonary sarcoidosis with progressive disease. Methotrexate or azathioprine may be used as steroid-sparing agents. Treatment duration is typically 12+ months with gradual taper.",
        "B", "Moderate",
        ["sarcoidosis", "pulmonary sarcoidosis"],
        ["prednisone", "methotrexate", "azathioprine", "infliximab"],
        ["pulmonary function tests", "chest ct", "ace level"],
        ["sarcoidosis", "granulomatous", "steroid", "methotrexate"],
    ),
    (
        "ATS/ERS Bronchiectasis",
        "ATS/ERS", 2024,
        "Non-CF Bronchiectasis Management",
        "Airway clearance techniques are the cornerstone of bronchiectasis management. Long-term macrolide therapy (azithromycin) reduces exacerbation frequency. Inhaled antibiotics may be considered for chronic Pseudomonas colonization.",
        "B", "Moderate",
        ["bronchiectasis", "chronic cough"],
        ["azithromycin", "tobramycin inhaled", "colistin inhaled"],
        ["sputum culture", "hrct chest"],
        ["bronchiectasis", "airway clearance", "macrolide", "pseudomonas"],
    ),
    (
        "ATS Occupational Lung Disease",
        "ATS", 2024,
        "Silicosis Surveillance and Management",
        "Workers with silica exposure should undergo periodic screening with chest radiography and spirometry. Removal from exposure is the primary intervention. No pharmacotherapy reverses established silicosis; supportive care and pulmonary rehabilitation are mainstays.",
        "C", "Moderate",
        ["silicosis", "occupational lung disease"],
        [],
        ["chest x-ray", "spirometry", "dlco"],
        ["silicosis", "occupational", "silica", "pneumoconiosis"],
    ),
    (
        "ATS/CHEST Pulmonary Hypertension Group 3",
        "ATS/CHEST", 2024,
        "PH in Chronic Lung Disease",
        "Supplemental oxygen to maintain SpO2 > 90% is recommended for Group 3 PH. PAH-specific vasodilators are generally not recommended for Group 3 PH except in select cases with severe hemodynamic impairment confirmed by right heart catheterization.",
        "B", "Moderate",
        ["pulmonary hypertension", "copd", "ild"],
        ["supplemental oxygen"],
        ["right heart catheterization", "echo", "nt-probnp"],
        ["group 3 ph", "lung disease", "pulmonary hypertension"],
    ),
    (
        "ATS/IDSA NTM Lung Disease",
        "ATS/IDSA", 2024,
        "NTM Pulmonary Infection Treatment",
        "MAC lung disease treatment includes macrolide-based regimen (azithromycin + ethambutol + rifampin) for at least 12 months after sputum culture conversion. M. abscessus requires IV amikacin + imipenem or cefoxitin induction followed by oral macrolide-based maintenance.",
        "B", "Strong",
        ["nontuberculous mycobacteria", "mac", "m abscessus"],
        ["azithromycin", "ethambutol", "rifampin", "amikacin"],
        ["sputum afb culture", "chest ct"],
        ["ntm", "mac", "mycobacteria", "macrolide"],
    ),
    # ── GI – additional topics ────────────────────────────────────────
    (
        "AASLD Autoimmune Hepatitis",
        "AASLD", 2024,
        "AIH Initial Treatment",
        "Prednisone (or budesonide for non-cirrhotic patients) combined with azathioprine is standard induction therapy for autoimmune hepatitis. Biochemical remission (normalization of ALT and IgG) should be achieved before considering maintenance therapy.",
        "A", "Strong",
        ["autoimmune hepatitis"],
        ["prednisone", "budesonide", "azathioprine", "mycophenolate"],
        ["alt", "ast", "igg level", "liver biopsy"],
        ["autoimmune hepatitis", "aih", "prednisone", "azathioprine"],
    ),
    (
        "AASLD Wilson Disease",
        "AASLD", 2024,
        "Wilson Disease Diagnosis and Treatment",
        "Diagnosis requires a combination of low ceruloplasmin, elevated 24-hour urine copper, and hepatic copper content on biopsy. D-penicillamine or trientine are first-line chelation therapy. Zinc maintenance may be used after initial decoppering.",
        "B", "Strong",
        ["wilson disease", "hepatolenticular degeneration"],
        ["d-penicillamine", "trientine", "zinc acetate"],
        ["ceruloplasmin", "24h urine copper", "liver biopsy copper"],
        ["wilson disease", "copper", "ceruloplasmin", "chelation"],
    ),
    (
        "ACG Achalasia",
        "ACG", 2024,
        "Achalasia Management",
        "Pneumatic dilation and laparoscopic Heller myotomy are the primary treatment options for type I and II achalasia. Per-oral endoscopic myotomy (POEM) is an effective alternative. Botulinum toxin injection is reserved for patients unfit for definitive therapy.",
        "B", "Strong",
        ["achalasia", "dysphagia"],
        ["botulinum toxin"],
        ["esophageal manometry", "barium swallow", "egd"],
        ["achalasia", "heller myotomy", "poem", "pneumatic dilation"],
    ),
    (
        "ACG Barrett Esophagus",
        "ACG", 2024,
        "Barrett Esophagus Surveillance",
        "Non-dysplastic Barrett esophagus requires surveillance EGD every 3-5 years. Low-grade dysplasia warrants endoscopic eradication therapy or surveillance every 6-12 months. High-grade dysplasia should undergo endoscopic eradication (radiofrequency ablation or endoscopic mucosal resection).",
        "B", "Strong",
        ["barrett esophagus", "gerd", "esophageal adenocarcinoma"],
        ["proton pump inhibitor"],
        ["egd with biopsy"],
        ["barrett", "dysplasia", "surveillance", "ablation"],
    ),
    (
        "ACG Gastroparesis",
        "ACG", 2024,
        "Gastroparesis Management",
        "Dietary modification (small, frequent, low-fat, low-fiber meals) is first-line. Metoclopramide is the only FDA-approved prokinetic; use should be limited to lowest effective dose for shortest duration. Gastric electrical stimulation may be considered for refractory symptoms.",
        "B", "Moderate",
        ["gastroparesis", "nausea", "vomiting"],
        ["metoclopramide", "domperidone", "erythromycin"],
        ["gastric emptying study", "egd"],
        ["gastroparesis", "prokinetic", "gastric emptying", "diabetic"],
    ),
    (
        "AASLD NAFLD/MASLD",
        "AASLD", 2024,
        "MASLD/NASH Management",
        "Lifestyle modification with weight loss of ≥7-10% is the primary treatment for MASLD/NASH. Resmetirom is approved for non-cirrhotic NASH with moderate-to-advanced fibrosis. Pioglitazone and vitamin E may be considered for biopsy-proven NASH in select patients.",
        "A", "Strong",
        ["metabolic dysfunction-associated steatotic liver disease", "nash", "nafld"],
        ["resmetirom", "pioglitazone", "vitamin e"],
        ["fibroscan", "fib-4", "liver biopsy", "alt"],
        ["masld", "nafld", "nash", "fatty liver", "fibrosis"],
    ),
    (
        "ACG Functional Dyspepsia",
        "ACG", 2024,
        "Functional Dyspepsia Treatment",
        "H. pylori test-and-treat is first-line. If negative, PPI trial for 4-8 weeks. Tricyclic antidepressants (amitriptyline 10-25 mg) are second-line for PPI non-responders. Prokinetics may benefit patients with postprandial distress syndrome.",
        "B", "Strong",
        ["functional dyspepsia", "epigastric pain"],
        ["omeprazole", "amitriptyline", "metoclopramide"],
        ["h pylori test", "egd"],
        ["dyspepsia", "functional", "ppi", "tca"],
    ),
    # ── Endocrinology – additional topics ─────────────────────────────
    (
        "Endocrine Society Cushing Syndrome",
        "Endocrine Society", 2024,
        "Cushing Syndrome Diagnosis",
        "At least two first-line screening tests should be abnormal: 24h urine free cortisol, late-night salivary cortisol, or 1 mg overnight dexamethasone suppression test. Once confirmed, ACTH levels and imaging differentiate ACTH-dependent from ACTH-independent causes.",
        "B", "Strong",
        ["cushing syndrome", "hypercortisolism"],
        ["dexamethasone"],
        ["24h urine free cortisol", "late-night salivary cortisol", "acth level", "dexamethasone suppression test"],
        ["cushing", "cortisol", "acth", "dexamethasone suppression"],
    ),
    (
        "Endocrine Society Pheochromocytoma",
        "Endocrine Society", 2024,
        "Pheochromocytoma Preoperative Management",
        "Alpha-adrenergic blockade (phenoxybenzamine or doxazosin) for minimum 10-14 days before surgery. Beta-blockers added only after adequate alpha-blockade to prevent hypertensive crisis. Liberal salt and fluid intake to expand intravascular volume.",
        "B", "Strong",
        ["pheochromocytoma", "paraganglioma"],
        ["phenoxybenzamine", "doxazosin", "propranolol"],
        ["plasma metanephrines", "24h urine catecholamines", "ct abdomen"],
        ["pheochromocytoma", "alpha blockade", "catecholamine", "adrenal"],
    ),
    (
        "Endocrine Society Acromegaly",
        "Endocrine Society", 2024,
        "Acromegaly Treatment",
        "Transsphenoidal surgery is first-line for most GH-secreting pituitary adenomas. Somatostatin receptor ligands (octreotide LAR, lanreotide) are first-line medical therapy if surgery is not curative. Pegvisomant is an alternative for persistently elevated IGF-1.",
        "B", "Strong",
        ["acromegaly", "growth hormone excess"],
        ["octreotide", "lanreotide", "pegvisomant", "cabergoline"],
        ["igf-1", "growth hormone", "pituitary mri"],
        ["acromegaly", "growth hormone", "somatostatin", "igf-1"],
    ),
    (
        "ADA Hypoglycemia",
        "ADA", 2024,
        "Hypoglycemia Management in Diabetes",
        "Level 1 hypoglycemia (54-70 mg/dL) requires fast-acting carbohydrate (15-20 g glucose). Level 2 (<54 mg/dL) requires glucagon availability and caregiver education. Continuous glucose monitoring reduces hypoglycemia risk in insulin-treated patients.",
        "A", "Strong",
        ["hypoglycemia", "diabetes mellitus"],
        ["glucose tablets", "glucagon", "insulin"],
        ["blood glucose", "cgm"],
        ["hypoglycemia", "glucose", "glucagon", "cgm"],
    ),
    (
        "Endocrine Society PCOS",
        "Endocrine Society", 2024,
        "PCOS Diagnosis and Management",
        "Diagnosis requires 2 of 3 Rotterdam criteria: oligo/anovulation, clinical/biochemical hyperandrogenism, polycystic ovarian morphology. Combined OCPs are first-line for menstrual irregularity and hyperandrogenism. Metformin improves metabolic parameters; lifestyle modification is fundamental.",
        "B", "Strong",
        ["polycystic ovary syndrome", "hyperandrogenism"],
        ["combined oral contraceptives", "metformin", "spironolactone"],
        ["testosterone", "dhea-s", "pelvic ultrasound", "glucose tolerance test"],
        ["pcos", "polycystic ovary", "hyperandrogenism", "anovulation"],
    ),
    (
        "ATA Thyroid Eye Disease",
        "ATA", 2024,
        "Thyroid Eye Disease Management",
        "Active moderate-to-severe TED is treated with IV glucocorticoids (methylprednisolone pulse therapy). Teprotumumab (IGF-1R inhibitor) is effective for proptosis and diplopia. Selenium supplementation may benefit mild active disease. Urgent orbital decompression for sight-threatening disease.",
        "B", "Strong",
        ["thyroid eye disease", "graves ophthalmopathy"],
        ["methylprednisolone", "teprotumumab", "selenium"],
        ["clinical activity score", "ct orbits", "visual acuity"],
        ["thyroid eye disease", "graves", "teprotumumab", "proptosis"],
    ),
    # ── Nephrology – additional topics ────────────────────────────────
    (
        "KDIGO Contrast-Associated AKI",
        "KDIGO", 2024,
        "Prevention of Contrast-Associated AKI",
        "IV isotonic saline hydration before and after contrast administration for patients at risk (eGFR <30, or eGFR 30-44 with additional risk factors). Use lowest possible contrast volume. Iso-osmolar or low-osmolar contrast agents preferred. Withhold metformin if eGFR <30.",
        "A", "Strong",
        ["contrast nephropathy", "acute kidney injury"],
        ["isotonic saline", "iodinated contrast"],
        ["serum creatinine", "egfr"],
        ["contrast", "nephropathy", "hydration", "aki prevention"],
    ),
    (
        "KDIGO Renal Artery Stenosis",
        "KDIGO", 2024,
        "Atherosclerotic Renal Artery Stenosis",
        "Medical therapy (ACE inhibitors/ARBs, statins, antiplatelet agents) is first-line for atherosclerotic RAS. Revascularization with stenting is considered for refractory hypertension, declining renal function, or flash pulmonary edema not responsive to medical therapy.",
        "A", "Strong",
        ["renal artery stenosis", "renovascular hypertension"],
        ["lisinopril", "losartan", "atorvastatin", "aspirin"],
        ["duplex ultrasound", "cta renal arteries", "serum creatinine"],
        ["renal artery stenosis", "renovascular", "stenting"],
    ),
    (
        "KDIGO Metabolic Acidosis in CKD",
        "KDIGO", 2024,
        "CKD-Associated Metabolic Acidosis",
        "Oral sodium bicarbonate supplementation is recommended for CKD patients with serum bicarbonate <22 mmol/L to slow GFR decline and improve nutritional status. Veverimer is a novel HCl binder under investigation. Dietary acid load reduction (fruits and vegetables) is an adjunct.",
        "B", "Moderate",
        ["metabolic acidosis", "chronic kidney disease"],
        ["sodium bicarbonate"],
        ["serum bicarbonate", "egfr", "venous blood gas"],
        ["metabolic acidosis", "ckd", "bicarbonate", "alkali therapy"],
    ),
    # ── Neurology – additional topics ─────────────────────────────────
    (
        "AAN ALS Guidelines",
        "AAN", 2024,
        "ALS Disease-Modifying Therapy",
        "Riluzole is recommended for all ALS patients to modestly extend survival. Edaravone may be considered though evidence of meaningful clinical benefit is limited. Tofersen is approved for SOD1-ALS. Multidisciplinary clinic care improves outcomes and quality of life.",
        "B", "Moderate",
        ["amyotrophic lateral sclerosis", "motor neuron disease"],
        ["riluzole", "edaravone", "tofersen"],
        ["fvc", "emg", "nerve conduction studies"],
        ["als", "motor neuron disease", "riluzole", "multidisciplinary"],
    ),
    (
        "AAN Normal Pressure Hydrocephalus",
        "AAN", 2024,
        "NPH Diagnosis and Treatment",
        "Clinical triad of gait disturbance, cognitive impairment, and urinary incontinence combined with ventriculomegaly out of proportion to sulcal enlargement. Large-volume LP (30-50 mL) with pre/post gait assessment aids diagnosis. VP shunting is the definitive treatment.",
        "C", "Moderate",
        ["normal pressure hydrocephalus"],
        [],
        ["brain mri", "lumbar puncture", "gait assessment"],
        ["nph", "hydrocephalus", "shunt", "gait apraxia"],
    ),
    (
        "AAN Narcolepsy",
        "AAN/AASM", 2024,
        "Narcolepsy Management",
        "Scheduled naps and good sleep hygiene are non-pharmacologic cornerstones. Modafinil or sodium oxybate are first-line pharmacotherapy. Solriamfetol and pitolisant are newer options. Sodium oxybate is the only therapy addressing both excessive daytime sleepiness and cataplexy.",
        "B", "Strong",
        ["narcolepsy", "cataplexy", "excessive daytime sleepiness"],
        ["modafinil", "sodium oxybate", "solriamfetol", "pitolisant"],
        ["mslt", "polysomnography", "csf hypocretin"],
        ["narcolepsy", "cataplexy", "modafinil", "sodium oxybate"],
    ),
    (
        "AAN Peripheral Neuropathy",
        "AAN", 2024,
        "Peripheral Neuropathy Evaluation",
        "Initial workup for distal symmetric polyneuropathy includes fasting glucose/HbA1c, B12, TSH, SPEP with immunofixation. Nerve conduction studies/EMG for atypical presentations. Treat underlying cause. Symptomatic treatment with duloxetine, pregabalin, or gabapentin.",
        "B", "Strong",
        ["peripheral neuropathy", "polyneuropathy"],
        ["duloxetine", "pregabalin", "gabapentin"],
        ["emg", "nerve conduction study", "hba1c", "vitamin b12"],
        ["neuropathy", "peripheral", "emg", "ncs"],
    ),
    (
        "AAN Guillain-Barré Syndrome",
        "AAN", 2024,
        "GBS Treatment",
        "IVIG (0.4 g/kg/day for 5 days) or plasma exchange (5 sessions over 2 weeks) are equally effective. Do not combine IVIG and PE. Corticosteroids are not beneficial. Monitor respiratory function closely; intubate for FVC <20 mL/kg or declining by >30%.",
        "A", "Strong",
        ["guillain-barre syndrome", "acute inflammatory demyelinating polyneuropathy"],
        ["ivig", "plasma exchange"],
        ["forced vital capacity", "nerve conduction studies", "csf protein"],
        ["gbs", "guillain-barre", "ivig", "plasma exchange"],
    ),
    # ── Rheumatology – additional topics ──────────────────────────────
    (
        "ACR Systemic Sclerosis",
        "ACR", 2024,
        "Systemic Sclerosis Skin and Lung Involvement",
        "Mycophenolate is first-line for SSc-ILD. Nintedanib may be added for progressive fibrosis. Raynaud phenomenon managed with CCBs (nifedipine); PDE5 inhibitors for digital ulcers. Autologous HSCT considered for rapidly progressive diffuse disease.",
        "B", "Moderate",
        ["systemic sclerosis", "scleroderma", "raynaud"],
        ["mycophenolate", "nintedanib", "nifedipine", "sildenafil"],
        ["pulmonary function tests", "hrct chest", "skin score"],
        ["scleroderma", "systemic sclerosis", "ild", "raynaud"],
    ),
    (
        "ACR Polymyalgia Rheumatica",
        "ACR/EULAR", 2024,
        "PMR Treatment",
        "Low-dose prednisone (12.5-25 mg/day) is first-line with gradual taper over 12-18 months. Methotrexate is recommended as steroid-sparing agent for patients with relapse, poor response, or steroid-related adverse effects. Screen for GCA symptoms at every visit.",
        "B", "Strong",
        ["polymyalgia rheumatica"],
        ["prednisone", "methotrexate"],
        ["esr", "crp", "temporal artery ultrasound"],
        ["pmr", "polymyalgia", "prednisone", "giant cell arteritis"],
    ),
    (
        "ACR Giant Cell Arteritis",
        "ACR/EULAR", 2024,
        "GCA Treatment",
        "High-dose prednisone (40-60 mg/day) initiated immediately upon clinical suspicion; do not delay for biopsy results. Tocilizumab is recommended as first-line steroid-sparing agent. Temporal artery biopsy or ultrasound for definitive diagnosis.",
        "A", "Strong",
        ["giant cell arteritis", "temporal arteritis"],
        ["prednisone", "tocilizumab"],
        ["esr", "crp", "temporal artery biopsy", "temporal artery ultrasound"],
        ["gca", "temporal arteritis", "tocilizumab", "vision loss"],
    ),
    (
        "ACR Sjögren Syndrome",
        "ACR", 2024,
        "Sjögren Syndrome Management",
        "Artificial tears and saliva substitutes for sicca symptoms. Pilocarpine or cevimeline for moderate-severe oral dryness. Hydroxychloroquine for systemic manifestations (arthralgia, fatigue). Rituximab for severe extraglandular disease. Screen for lymphoma at regular intervals.",
        "B", "Moderate",
        ["sjogren syndrome", "sicca syndrome"],
        ["pilocarpine", "cevimeline", "hydroxychloroquine", "rituximab"],
        ["schirmer test", "salivary flow rate", "anti-ssa", "anti-ssb"],
        ["sjogren", "sicca", "dry eyes", "dry mouth"],
    ),
    (
        "ACR Dermatomyositis/Polymyositis",
        "ACR", 2024,
        "Inflammatory Myopathy Treatment",
        "High-dose prednisone (1 mg/kg/day) is first-line for PM/DM. Methotrexate or azathioprine as steroid-sparing agents. IVIG for refractory disease or dysphagia. Screen for malignancy (especially within first 3 years of DM diagnosis) and ILD with HRCT and PFTs.",
        "B", "Strong",
        ["dermatomyositis", "polymyositis", "inflammatory myopathy"],
        ["prednisone", "methotrexate", "azathioprine", "ivig", "rituximab"],
        ["ck", "aldolase", "emg", "mri muscle", "myositis antibody panel"],
        ["myositis", "dermatomyositis", "polymyositis", "ck"],
    ),
    # ── Hematology – additional topics ────────────────────────────────
    (
        "ASH Sickle Cell Disease",
        "ASH", 2024,
        "SCD Disease-Modifying Therapy",
        "Hydroxyurea is recommended for all patients ≥9 months with SCA (HbSS/HbSβ0) regardless of clinical severity. Voxelotor and crizanlizumab are add-on therapies. L-glutamine may reduce pain crises. Curative options include matched sibling donor HSCT and gene therapy.",
        "A", "Strong",
        ["sickle cell disease", "sickle cell anemia"],
        ["hydroxyurea", "voxelotor", "crizanlizumab", "l-glutamine"],
        ["hemoglobin electrophoresis", "reticulocyte count", "ldh"],
        ["sickle cell", "hydroxyurea", "voxelotor", "gene therapy"],
    ),
    (
        "ASH Sickle Cell Disease",
        "ASH", 2024,
        "SCD Acute Vaso-Occlusive Crisis",
        "Rapid pain assessment and IV opioid administration within 30 minutes of presentation. NSAIDs as adjunct. IV fluids at maintenance rate (avoid overhydration). Incentive spirometry to prevent acute chest syndrome. Blood transfusion for severe anemia or acute chest syndrome.",
        "A", "Strong",
        ["sickle cell disease", "vaso-occlusive crisis", "acute chest syndrome"],
        ["morphine", "hydromorphone", "ketorolac"],
        ["cbc", "reticulocyte count", "chest x-ray"],
        ["voc", "sickle cell crisis", "acute chest syndrome", "pain"],
    ),
    (
        "ASH ITP",
        "ASH", 2024,
        "Immune Thrombocytopenia Management",
        "Observation for asymptomatic ITP with platelets >30,000. First-line: corticosteroids (dexamethasone 40 mg x4 days or prednisone 1 mg/kg). Second-line: TPO-RAs (eltrombopag, romiplostim), rituximab, or splenectomy. IVIG for severe bleeding or urgent platelet increase.",
        "A", "Strong",
        ["immune thrombocytopenia", "itp"],
        ["dexamethasone", "prednisone", "eltrombopag", "romiplostim", "rituximab", "ivig"],
        ["platelet count", "peripheral blood smear"],
        ["itp", "thrombocytopenia", "tpo-ra", "rituximab"],
    ),
    (
        "ASH TTP",
        "ASH", 2024,
        "Thrombotic Thrombocytopenic Purpura",
        "Immediate plasma exchange (PEX) is the cornerstone of TTP treatment. Caplacizumab (anti-vWF nanobody) reduces time to platelet normalization and recurrence. Corticosteroids and rituximab added for immune-mediated TTP. ADAMTS13 activity <10% confirms diagnosis.",
        "A", "Strong",
        ["thrombotic thrombocytopenic purpura", "ttp"],
        ["caplacizumab", "rituximab", "methylprednisolone"],
        ["adamts13 activity", "platelet count", "ldh", "peripheral blood smear"],
        ["ttp", "plasma exchange", "adamts13", "caplacizumab"],
    ),
    (
        "NCCN Myelodysplastic Syndromes",
        "NCCN", 2025,
        "Lower-Risk MDS Treatment",
        "Observation for asymptomatic lower-risk MDS. ESAs (epoetin alfa, darbepoetin) for symptomatic anemia with low endogenous EPO. Luspatercept for ESA-refractory anemia. Lenalidomide for del(5q) MDS. Hypomethylating agents for higher-risk MDS.",
        "B", "Strong",
        ["myelodysplastic syndrome", "anemia"],
        ["epoetin alfa", "darbepoetin", "luspatercept", "lenalidomide", "azacitidine"],
        ["cbc", "bone marrow biopsy", "cytogenetics", "epo level"],
        ["mds", "myelodysplastic", "esa", "lenalidomide"],
    ),
    (
        "ASH Hemophilia",
        "ASH/WFH", 2024,
        "Hemophilia A Management",
        "Prophylaxis with factor VIII replacement is standard of care for severe hemophilia A. Extended half-life products reduce infusion frequency. Emicizumab (bispecific antibody) is an alternative for prophylaxis regardless of inhibitor status. Gene therapy (valoctocogene roxaparvovec) is available for select adults.",
        "A", "Strong",
        ["hemophilia a", "factor viii deficiency"],
        ["factor viii concentrate", "emicizumab", "valoctocogene roxaparvovec"],
        ["factor viii level", "inhibitor titer", "aptt"],
        ["hemophilia", "factor viii", "emicizumab", "gene therapy"],
    ),
    # ── Infectious Disease – additional topics ────────────────────────
    (
        "IDSA Herpes Zoster",
        "IDSA/AAD", 2024,
        "Herpes Zoster Treatment",
        "Oral antivirals (valacyclovir 1g TID or acyclovir 800mg 5x/day) initiated within 72 hours of rash onset for 7 days. IV acyclovir for disseminated disease or immunocompromised patients. Postherpetic neuralgia managed with gabapentin, pregabalin, or topical lidocaine. Shingrix vaccine for prevention in adults ≥50.",
        "A", "Strong",
        ["herpes zoster", "shingles", "postherpetic neuralgia"],
        ["valacyclovir", "acyclovir", "gabapentin", "pregabalin"],
        ["clinical diagnosis", "tzanck smear", "pcr"],
        ["herpes zoster", "shingles", "antiviral", "postherpetic neuralgia"],
    ),
    (
        "IDSA Influenza Treatment",
        "IDSA", 2024,
        "Influenza Antiviral Treatment",
        "Oseltamivir within 48 hours of symptom onset for high-risk patients, hospitalized patients, and those with severe illness. Baloxavir marboxil is a single-dose alternative. Peramivir IV for patients unable to take oral/inhaled antivirals. Do not delay treatment awaiting confirmatory testing.",
        "A", "Strong",
        ["influenza", "flu"],
        ["oseltamivir", "baloxavir marboxil", "peramivir", "zanamivir"],
        ["rapid influenza test", "influenza pcr"],
        ["influenza", "oseltamivir", "baloxavir", "antiviral"],
    ),
    (
        "IDSA Prosthetic Joint Infection",
        "IDSA", 2024,
        "PJI Treatment Strategy",
        "Acute PJI (<30 days postoperative or <3 weeks symptom duration) may be treated with DAIR (debridement, antibiotics, implant retention). Chronic PJI requires two-stage exchange arthroplasty. Pathogen-specific antibiotic therapy for 6-12 weeks including rifampin for staphylococcal PJI with retained implant.",
        "B", "Strong",
        ["prosthetic joint infection", "periprosthetic infection"],
        ["vancomycin", "ceftriaxone", "rifampin", "daptomycin"],
        ["synovial fluid analysis", "alpha-defensin", "joint aspiration wbc"],
        ["prosthetic joint infection", "pji", "dair", "two-stage exchange"],
    ),
    (
        "IDSA Pharyngitis",
        "IDSA", 2024,
        "Group A Strep Pharyngitis",
        "Confirm GAS pharyngitis with rapid antigen detection test or throat culture before antibiotic treatment. Amoxicillin or penicillin V for 10 days is first-line. Single IM benzathine penicillin G for non-adherent patients. Centor/McIsaac score guides testing need.",
        "A", "Strong",
        ["pharyngitis", "streptococcal pharyngitis", "sore throat"],
        ["amoxicillin", "penicillin v", "benzathine penicillin g", "azithromycin"],
        ["rapid strep test", "throat culture"],
        ["strep pharyngitis", "gas", "amoxicillin", "centor score"],
    ),
    (
        "CDC Sexually Transmitted Infections",
        "CDC", 2024,
        "Gonorrhea Treatment Update",
        "Ceftriaxone 500 mg IM single dose (1 g for patients ≥150 kg) is recommended for uncomplicated gonococcal infections (urogenital, rectal, pharyngeal). Test of cure at 7-14 days for pharyngeal gonorrhea. Test for chlamydia co-infection and treat if present.",
        "A", "Strong",
        ["gonorrhea", "neisseria gonorrhoeae"],
        ["ceftriaxone", "doxycycline"],
        ["naat gonorrhea", "culture and sensitivity"],
        ["gonorrhea", "ceftriaxone", "sti", "naat"],
    ),
    (
        "CDC Sexually Transmitted Infections",
        "CDC", 2024,
        "Chlamydia Treatment",
        "Doxycycline 100 mg BID for 7 days is preferred for chlamydial urogenital, rectal, and oropharyngeal infections (superior to azithromycin for rectal chlamydia). Azithromycin 1 g single dose is an alternative. Test of cure at 4 weeks for pregnant patients.",
        "A", "Strong",
        ["chlamydia", "chlamydia trachomatis"],
        ["doxycycline", "azithromycin"],
        ["naat chlamydia"],
        ["chlamydia", "doxycycline", "sti", "naat"],
    ),
    (
        "CDC Syphilis Treatment",
        "CDC", 2024,
        "Syphilis Treatment by Stage",
        "Primary, secondary, and early latent syphilis: benzathine penicillin G 2.4 MU IM single dose. Late latent or unknown duration: benzathine penicillin G 2.4 MU IM weekly x3 weeks. Neurosyphilis: IV aqueous penicillin G 18-24 MU/day for 10-14 days.",
        "A", "Strong",
        ["syphilis", "neurosyphilis"],
        ["benzathine penicillin g", "aqueous penicillin g", "doxycycline"],
        ["rpr", "vdrl", "fta-abs", "csf analysis"],
        ["syphilis", "penicillin", "rpr", "treponema"],
    ),
    # ── Dermatology – additional topics ───────────────────────────────
    (
        "AAD Urticaria Guidelines",
        "AAD", 2024,
        "Chronic Spontaneous Urticaria",
        "Second-generation H1-antihistamines at standard dose are first-line. Up-titration to 4x standard dose if inadequate response. Omalizumab is recommended as add-on for antihistamine-refractory CSU. Cyclosporine is third-line. Avoid systemic corticosteroids for chronic use.",
        "A", "Strong",
        ["chronic urticaria", "chronic spontaneous urticaria"],
        ["cetirizine", "loratadine", "fexofenadine", "omalizumab", "cyclosporine"],
        ["cbc", "crp", "tsh", "urticaria activity score"],
        ["urticaria", "hives", "omalizumab", "antihistamine"],
    ),
    (
        "AAD Drug Reactions",
        "AAD", 2024,
        "Severe Cutaneous Adverse Drug Reactions",
        "Immediate discontinuation of suspected causative agent for SJS/TEN. Transfer to burn unit for TEN (>30% BSA). IVIG or cyclosporine may be considered for TEN though evidence is limited. DRESS syndrome requires systemic corticosteroids. Document allergy and provide drug avoidance counseling.",
        "B", "Strong",
        ["stevens-johnson syndrome", "toxic epidermal necrolysis", "dress syndrome"],
        ["cyclosporine", "ivig", "prednisone"],
        ["skin biopsy", "cbc", "eosinophil count", "liver function tests"],
        ["sjs", "ten", "dress", "drug reaction", "scar"],
    ),
    (
        "AAD Fungal Skin Infections",
        "AAD", 2024,
        "Tinea Capitis Management",
        "Systemic antifungal therapy is required for tinea capitis (topical therapy alone is insufficient). Griseofulvin or terbinafine for 4-8 weeks depending on causative organism. Terbinafine preferred for Trichophyton; griseofulvin for Microsporum. Adjunctive antifungal shampoo reduces transmission.",
        "A", "Strong",
        ["tinea capitis", "scalp ringworm"],
        ["griseofulvin", "terbinafine", "ketoconazole shampoo"],
        ["koh preparation", "fungal culture"],
        ["tinea capitis", "ringworm", "griseofulvin", "terbinafine"],
    ),
    (
        "AAD Vitiligo",
        "AAD", 2024,
        "Vitiligo Treatment Options",
        "Topical corticosteroids (class III-IV) are first-line for localized vitiligo. Topical calcineurin inhibitors (tacrolimus) for facial/intertriginous areas. Ruxolitinib cream (JAK inhibitor) is FDA-approved for non-segmental vitiligo. Narrowband UVB phototherapy for widespread disease.",
        "B", "Moderate",
        ["vitiligo"],
        ["clobetasol", "tacrolimus", "ruxolitinib cream"],
        [],
        ["vitiligo", "repigmentation", "jak inhibitor", "phototherapy"],
    ),
    # ── Ophthalmology – additional topics ─────────────────────────────
    (
        "AAO Cataract Surgery",
        "AAO", 2024,
        "Cataract Surgery Indications and Technique",
        "Surgery is indicated when visual impairment from cataract affects quality of life or interferes with essential activities. Phacoemulsification with posterior chamber IOL implantation is standard technique. Preoperative biometry for IOL power calculation. Topical NSAID + antibiotic postoperatively.",
        "A", "Strong",
        ["cataract", "phacoemulsification"],
        ["ketorolac ophthalmic", "moxifloxacin ophthalmic"],
        ["visual acuity", "slit lamp exam", "iol biometry"],
        ["cataract", "phacoemulsification", "iol", "visual acuity"],
    ),
    (
        "AAO Dry Eye Disease",
        "AAO", 2024,
        "Dry Eye Management Stepwise",
        "Step 1: Education, environmental modification, artificial tears, lid hygiene. Step 2: Cyclosporine or lifitegrast drops, punctal plugs. Step 3: Autologous serum tears, therapeutic contact lenses. Step 4: Systemic anti-inflammatory therapy, amniotic membrane. Assess for Meibomian gland dysfunction.",
        "B", "Moderate",
        ["dry eye disease", "keratoconjunctivitis sicca"],
        ["artificial tears", "cyclosporine ophthalmic", "lifitegrast"],
        ["tear breakup time", "schirmer test", "osmolarity"],
        ["dry eye", "meibomian", "cyclosporine", "artificial tears"],
    ),
    # ── Pediatrics – additional topics ────────────────────────────────
    (
        "AAP Neonatal Sepsis",
        "AAP", 2024,
        "Early-Onset Neonatal Sepsis Evaluation",
        "Risk-based approach using sepsis calculator or categorical risk factors for EOS evaluation. Empiric ampicillin + gentamicin for suspected EOS. Blood culture before antibiotics when possible. Discontinue antibiotics at 36-48 hours if cultures negative and infant is clinically well.",
        "A", "Strong",
        ["neonatal sepsis", "early-onset sepsis"],
        ["ampicillin", "gentamicin"],
        ["blood culture", "cbc", "crp", "procalcitonin"],
        ["neonatal sepsis", "eos", "ampicillin", "gentamicin"],
    ),
    (
        "AAP Food Allergy Prevention",
        "AAP/NIAID", 2024,
        "Early Peanut Introduction",
        "For infants at high risk (severe eczema or egg allergy), introduce peanut-containing foods around 4-6 months after evaluation (including possible skin prick testing). For moderate-risk infants, introduce around 6 months. Early introduction significantly reduces peanut allergy development.",
        "A", "Strong",
        ["food allergy", "peanut allergy"],
        [],
        ["skin prick test", "serum ige"],
        ["peanut allergy", "food allergy", "early introduction", "leap"],
    ),
    (
        "AAP Adolescent Depression",
        "AAP", 2024,
        "Adolescent Depression Management",
        "PHQ-A screening in primary care for adolescents ≥12. Mild-moderate depression: active support, psychoeducation, and CBT. Fluoxetine is first-line pharmacotherapy; escitalopram approved for ≥12 years. Black box monitoring: weekly visits first month, biweekly for second month. Combination therapy (CBT + SSRI) is most effective for moderate-severe depression.",
        "A", "Strong",
        ["adolescent depression", "major depressive disorder"],
        ["fluoxetine", "escitalopram"],
        ["phq-a", "columbia suicide severity rating scale"],
        ["adolescent depression", "ssri", "cbt", "black box"],
    ),
    (
        "AAP Adolescent Substance Use",
        "AAP", 2024,
        "SBIRT for Adolescent Substance Use",
        "Universal screening for substance use at annual well-visits using validated tools (CRAFFT 2.1). Brief intervention for at-risk use. Referral to treatment for substance use disorder. Confidentiality protections for adolescents. Avoid urine drug screens without informed consent.",
        "B", "Strong",
        ["substance use disorder", "adolescent substance use"],
        [],
        ["crafft screening", "urine drug screen"],
        ["sbirt", "adolescent", "substance use", "crafft", "screening"],
    ),
    (
        "AAP Pediatric Obesity",
        "AAP", 2024,
        "Pediatric Obesity Comprehensive Management",
        "Intensive health behavior and lifestyle treatment (≥26 contact hours over 3-12 months) is recommended for children ≥6 with BMI ≥95th percentile. Pharmacotherapy (GLP-1 RAs) may be offered for ≥12 years with obesity. Metabolic/bariatric surgery for adolescents ≥13 with severe obesity and comorbidities.",
        "A", "Strong",
        ["pediatric obesity", "childhood obesity"],
        ["semaglutide", "liraglutide"],
        ["bmi percentile", "fasting glucose", "lipid panel", "alt"],
        ["pediatric obesity", "glp-1", "bariatric", "lifestyle"],
    ),
    # ── Surgery – additional topics ───────────────────────────────────
    (
        "ACS Trauma Quality Programs",
        "ACS", 2024,
        "Massive Transfusion Protocol",
        "Activate MTP for patients with hemorrhagic shock or anticipated need for >10 units pRBC in 24 hours. Target 1:1:1 ratio (pRBC:FFP:platelets). Tranexamic acid within 3 hours of injury. Limit crystalloid resuscitation. Viscoelastic testing (TEG/ROTEM) for goal-directed therapy.",
        "A", "Strong",
        ["hemorrhagic shock", "massive transfusion", "trauma"],
        ["packed red blood cells", "fresh frozen plasma", "platelets", "tranexamic acid"],
        ["hemoglobin", "inr", "fibrinogen", "teg", "rotem"],
        ["massive transfusion", "hemorrhage", "txa", "damage control resuscitation"],
    ),
    (
        "ACS NSQIP Perioperative Safety",
        "ACS", 2024,
        "Enhanced Recovery After Surgery – Colorectal",
        "Multimodal opioid-sparing analgesia, early mobilization, early enteral nutrition (POD 0), and goal-directed fluid therapy. Alvimopan for accelerating GI recovery after bowel resection with primary anastomosis. Mechanical bowel prep with oral antibiotics reduces SSI for elective colorectal surgery.",
        "A", "Strong",
        ["colorectal surgery", "postoperative recovery"],
        ["acetaminophen", "ketorolac", "gabapentin", "alvimopan", "lidocaine patch"],
        [],
        ["eras", "colorectal", "enhanced recovery", "opioid-sparing"],
    ),
    (
        "ACS Acute Care Surgery",
        "ACS/EAST", 2024,
        "Small Bowel Obstruction Management",
        "Non-operative management (NGT decompression, IV fluids, NPO) for adhesive SBO without signs of strangulation. Water-soluble contrast (Gastrografin) challenge at 24-48 hours: contrast in colon on follow-up X-ray predicts resolution. Surgical intervention for complete obstruction, signs of strangulation, or failure to resolve in 3-5 days.",
        "B", "Strong",
        ["small bowel obstruction", "adhesive bowel obstruction"],
        ["gastrografin"],
        ["ct abdomen", "abdominal x-ray", "lactate"],
        ["sbo", "bowel obstruction", "adhesive", "gastrografin"],
    ),
    (
        "SIS Surgical Site Infection Prevention",
        "SIS/SHEA", 2024,
        "SSI Prevention Bundle",
        "Preoperative chlorhexidine bathing, appropriate antibiotic prophylaxis within 60 minutes of incision, intraoperative normothermia, glycemic control (<180 mg/dL), and supplemental oxygen. Weight-based antibiotic dosing and redosing for prolonged procedures. Avoid routine postoperative antibiotic extension.",
        "A", "Strong",
        ["surgical site infection", "wound infection"],
        ["cefazolin", "chlorhexidine"],
        ["wound culture", "temperature", "blood glucose"],
        ["ssi prevention", "surgical prophylaxis", "chlorhexidine", "bundle"],
    ),
    # ── Emergency Medicine – additional topics ────────────────────────
    (
        "ACEP Procedural Sedation",
        "ACEP", 2024,
        "ED Procedural Sedation Safety",
        "Propofol and ketamine are first-line agents for ED procedural sedation. Continuous monitoring (pulse oximetry, capnography, cardiac monitor) is required. Fasting status does not alter management in emergency settings. Personnel skilled in airway management must be present. Pre-procedural risk assessment using ASA classification.",
        "A", "Strong",
        ["procedural sedation", "conscious sedation"],
        ["propofol", "ketamine", "midazolam", "fentanyl"],
        ["pulse oximetry", "capnography", "blood pressure"],
        ["procedural sedation", "propofol", "ketamine", "capnography"],
    ),
    (
        "ACEP Acute Stroke",
        "ACEP/AHA", 2024,
        "Acute Ischemic Stroke – Door-to-Needle Time",
        "IV alteplase within 4.5 hours of symptom onset for eligible patients. Target door-to-needle time <60 minutes. Mechanical thrombectomy for large vessel occlusion up to 24 hours with favorable perfusion imaging. Tenecteplase (0.25 mg/kg) is emerging as alternative to alteplase.",
        "A", "Strong",
        ["acute ischemic stroke", "large vessel occlusion"],
        ["alteplase", "tenecteplase"],
        ["nihss", "ct head", "cta", "ct perfusion"],
        ["stroke", "thrombolysis", "thrombectomy", "door-to-needle"],
    ),
    (
        "ACEP Suicidal Ideation",
        "ACEP", 2024,
        "ED Suicide Risk Assessment",
        "Universal screening with validated tools (Columbia Suicide Severity Rating Scale). Safety planning intervention before discharge for patients with suicidal ideation but low acute risk. Lethal means counseling (firearms, medications). Psychiatric consultation for moderate-high risk. No evidence supports mandatory prolonged observation for all presentations.",
        "B", "Strong",
        ["suicidal ideation", "suicide risk"],
        [],
        ["c-ssrs", "phq-9 question 9"],
        ["suicide", "risk assessment", "safety planning", "c-ssrs"],
    ),
    (
        "ACEP Sepsis Bundle",
        "ACEP/SSC", 2024,
        "ED Sepsis Recognition and Hour-1 Bundle",
        "Measure lactate. Obtain blood cultures before antibiotics. Administer broad-spectrum antibiotics within 1 hour. Begin 30 mL/kg crystalloid for hypotension or lactate ≥4. Reassess volume status and tissue perfusion. Vasopressors if MAP <65 after fluid resuscitation.",
        "A", "Strong",
        ["sepsis", "septic shock"],
        ["piperacillin-tazobactam", "meropenem", "vancomycin", "norepinephrine"],
        ["lactate", "blood culture", "procalcitonin", "map"],
        ["sepsis", "hour-1 bundle", "lactate", "broad-spectrum antibiotics"],
    ),
    # ── Allergy/Immunology – additional topics ────────────────────────
    (
        "AAAAI Allergic Rhinitis",
        "AAAAI", 2024,
        "Allergic Rhinitis Stepwise Treatment",
        "Intranasal corticosteroids are the most effective monotherapy for moderate-severe allergic rhinitis. Second-generation antihistamines for mild symptoms. Allergen immunotherapy (subcutaneous or sublingual) for patients with inadequate response to pharmacotherapy. Avoid first-generation antihistamines due to sedation.",
        "A", "Strong",
        ["allergic rhinitis", "hay fever"],
        ["fluticasone nasal", "mometasone nasal", "cetirizine", "loratadine"],
        ["skin prick test", "serum ige"],
        ["allergic rhinitis", "intranasal steroid", "immunotherapy"],
    ),
    (
        "AAAAI Chronic Sinusitis",
        "AAAAI/ARS", 2024,
        "Chronic Rhinosinusitis Management",
        "Nasal saline irrigation and intranasal corticosteroids are first-line. For CRSwNP, biologic therapy (dupilumab, omalizumab, mepolizumab) is recommended for refractory cases. Short-course oral corticosteroids for acute exacerbations. Endoscopic sinus surgery for persistent symptoms despite medical therapy.",
        "B", "Strong",
        ["chronic rhinosinusitis", "nasal polyps"],
        ["fluticasone nasal", "dupilumab", "omalizumab", "mepolizumab"],
        ["ct sinuses", "nasal endoscopy"],
        ["chronic sinusitis", "nasal polyps", "biologic", "dupilumab"],
    ),
    (
        "AAAAI Asthma Biologics",
        "AAAAI/ATS", 2024,
        "Biologic Therapy for Severe Asthma",
        "Phenotype-guided biologic selection: omalizumab for allergic asthma (elevated IgE), mepolizumab/benralizumab for eosinophilic asthma (blood eos ≥150), dupilumab for Type 2 inflammation (eos ≥150 or FeNO ≥25), tezepelumab for broad severe asthma population regardless of phenotype.",
        "A", "Strong",
        ["severe asthma", "refractory asthma"],
        ["omalizumab", "mepolizumab", "benralizumab", "dupilumab", "tezepelumab"],
        ["blood eosinophils", "total ige", "feno", "spirometry"],
        ["biologic", "severe asthma", "eosinophilic", "omalizumab", "dupilumab"],
    ),
    (
        "AAAAI Atopic Dermatitis Systemic",
        "AAAAI/AAD", 2024,
        "Systemic Therapy for Moderate-Severe AD",
        "Dupilumab is first-line systemic therapy for moderate-severe AD in adults and children ≥6 months. JAK inhibitors (abrocitinib, upadacitinib) are alternatives. Tralokinumab for adults. Traditional immunosuppressants (cyclosporine, methotrexate) are less preferred due to safety profile.",
        "A", "Strong",
        ["atopic dermatitis", "eczema"],
        ["dupilumab", "abrocitinib", "upadacitinib", "tralokinumab", "cyclosporine"],
        ["easi score", "iga score", "total ige"],
        ["atopic dermatitis", "dupilumab", "jak inhibitor", "biologic"],
    ),
    # ── Geriatrics – additional topics ────────────────────────────────
    (
        "AGS Polypharmacy",
        "AGS", 2024,
        "Deprescribing in Older Adults",
        "Regular medication review to identify potentially inappropriate medications. Apply STOPPFrail or Beers Criteria for deprescribing candidates. Prioritize deprescribing PPIs, benzodiazepines, anticholinergics, and medications without ongoing indication. Taper gradually; monitor for withdrawal or return of symptoms.",
        "B", "Moderate",
        ["polypharmacy", "deprescribing"],
        [],
        [],
        ["polypharmacy", "deprescribing", "beers criteria", "stoppfrail"],
    ),
    (
        "AGS Delirium in Older Adults",
        "AGS/APA", 2024,
        "Delirium Prevention and Management",
        "Non-pharmacologic multicomponent prevention (HELP model): reorientation, early mobilization, sleep promotion, hydration, vision/hearing optimization. Treat underlying cause. Avoid antipsychotics unless severe agitation threatening safety. Low-dose haloperidol if absolutely necessary; avoid in QTc prolongation or Lewy body dementia.",
        "A", "Strong",
        ["delirium", "acute confusional state"],
        ["haloperidol"],
        ["cam", "4at", "qrs interval"],
        ["delirium", "prevention", "help model", "non-pharmacologic"],
    ),
    (
        "AGS Falls Prevention Comprehensive",
        "AGS/BGS", 2024,
        "Multifactorial Falls Prevention",
        "Annual falls screening for community-dwelling adults ≥65. Multifactorial risk assessment: gait/balance testing, medication review, orthostatic vitals, visual acuity, home safety. Exercise programs (balance + strength) reduce falls 23%. Vitamin D supplementation if deficient. Review/reduce fall-risk medications.",
        "A", "Strong",
        ["falls", "fall prevention", "gait disorder"],
        ["vitamin d"],
        ["timed up and go", "orthostatic blood pressure", "visual acuity"],
        ["falls prevention", "balance", "multifactorial", "exercise"],
    ),
    # ── Preventive Medicine – additional topics ───────────────────────
    (
        "USPSTF HIV Screening",
        "USPSTF", 2024,
        "HIV Screening Recommendations",
        "Screen all persons aged 15-65 and all pregnant persons. Younger adolescents and older adults at increased risk should also be screened. Fourth-generation HIV Ag/Ab combination assays are recommended. Repeat screening based on ongoing risk factors.",
        "A", "Strong",
        ["hiv screening", "hiv prevention"],
        [],
        ["hiv ag/ab combo", "hiv viral load"],
        ["hiv screening", "uspstf", "fourth generation", "prevention"],
    ),
    (
        "USPSTF Hepatitis C Screening",
        "USPSTF", 2024,
        "HCV Universal Screening",
        "Screen all adults aged 18-79 for hepatitis C at least once. One-time HCV antibody test; if reactive, confirm with HCV RNA. All persons with active HCV should be linked to treatment with direct-acting antivirals regardless of fibrosis stage.",
        "A", "Strong",
        ["hepatitis c", "hcv screening"],
        ["sofosbuvir-velpatasvir", "glecaprevir-pibrentasvir"],
        ["hcv antibody", "hcv rna"],
        ["hepatitis c screening", "hcv", "universal screening", "daa"],
    ),
    (
        "USPSTF Prediabetes/Diabetes Screening",
        "USPSTF", 2024,
        "Type 2 Diabetes Screening",
        "Screen adults aged 35-70 who are overweight or obese. Fasting plasma glucose, HbA1c, or oral glucose tolerance test. Refer patients with prediabetes to intensive behavioral counseling (Diabetes Prevention Program). Rescreen every 3 years if initial results are normal.",
        "B", "Moderate",
        ["prediabetes", "type 2 diabetes screening"],
        ["metformin"],
        ["fasting glucose", "hba1c", "oral glucose tolerance test"],
        ["diabetes screening", "prediabetes", "dpp", "uspstf"],
    ),
    (
        "USPSTF Breast Cancer Screening",
        "USPSTF", 2024,
        "Mammography Screening Recommendations",
        "Biennial screening mammography for women aged 40-74. Decision to start at 40 should be individualized considering risk factors. Insufficient evidence for screening after age 74. Supplemental MRI screening for women with extremely dense breasts or high lifetime risk (>20%).",
        "B", "Moderate",
        ["breast cancer screening", "mammography"],
        [],
        ["mammography", "breast mri"],
        ["mammography", "breast cancer screening", "uspstf", "dense breasts"],
    ),
    (
        "USPSTF Statin Use for CVD Prevention",
        "USPSTF", 2024,
        "Statin Primary Prevention",
        "Prescribe statins for adults aged 40-75 with one or more CVD risk factors (dyslipidemia, diabetes, hypertension, smoking) and 10-year ASCVD risk ≥10%. Moderate-intensity statin is appropriate for primary prevention. Shared decision-making for 7.5-10% risk range.",
        "B", "Moderate",
        ["cardiovascular disease prevention", "hyperlipidemia"],
        ["atorvastatin", "rosuvastatin", "pravastatin"],
        ["lipid panel", "ascvd risk score"],
        ["statin", "primary prevention", "ascvd", "uspstf"],
    ),
    (
        "ACSM Exercise Prescription",
        "ACSM", 2024,
        "Exercise Prescription for Chronic Disease",
        "150-300 minutes/week moderate-intensity or 75-150 minutes/week vigorous-intensity aerobic activity. Resistance training ≥2 days/week targeting major muscle groups. Additional benefits with flexibility and balance exercises for older adults. Pre-exercise evaluation for individuals with known CVD or high risk.",
        "A", "Strong",
        ["physical inactivity", "exercise prescription"],
        [],
        ["vo2 max", "6-minute walk test", "heart rate"],
        ["exercise prescription", "physical activity", "aerobic", "resistance"],
    ),
    # ── Pain Medicine – additional topics ─────────────────────────────
    (
        "APS/ASRA Chronic Pain",
        "APS/ASRA", 2024,
        "Chronic Non-Cancer Pain – Multimodal Approach",
        "Multimodal pain management combining physical therapy, cognitive behavioral therapy, non-opioid pharmacotherapy (acetaminophen, NSAIDs, duloxetine, gabapentinoids), and interventional procedures. Opioids reserved for refractory cases with careful risk-benefit assessment and ongoing monitoring. Implement ORT and PDMP checks.",
        "A", "Strong",
        ["chronic pain", "chronic non-cancer pain"],
        ["acetaminophen", "naproxen", "duloxetine", "gabapentin", "pregabalin"],
        ["pain vas", "functional assessment"],
        ["chronic pain", "multimodal", "non-opioid", "opioid risk"],
    ),
    (
        "AAN Low Back Pain",
        "AAN/ACP", 2024,
        "Acute Low Back Pain Management",
        "Self-care education and reassurance. NSAIDs as first-line pharmacotherapy. Skeletal muscle relaxants as short-term adjunct. Avoid imaging in absence of red flags (progressive neurological deficit, suspected cancer, cauda equina). Physical therapy for subacute/chronic LBP. Avoid opioids for acute nonspecific LBP.",
        "A", "Strong",
        ["acute low back pain", "lumbago"],
        ["ibuprofen", "naproxen", "cyclobenzaprine"],
        [],
        ["low back pain", "nsaid", "red flags", "avoid imaging"],
    ),
    (
        "ASRA Interventional Pain",
        "ASRA", 2024,
        "Epidural Steroid Injection Guidance",
        "ESIs provide short-term relief for radicular pain associated with disc herniation or spinal stenosis. Fluoroscopic guidance is standard for accuracy and safety. Limit to 3-4 injections per year. Not recommended for axial back pain without radiculopathy. Consider in context of comprehensive pain management plan.",
        "B", "Moderate",
        ["radiculopathy", "spinal stenosis", "disc herniation"],
        ["methylprednisolone", "triamcinolone", "dexamethasone"],
        ["mri spine", "emg"],
        ["epidural injection", "radiculopathy", "fluoroscopic", "steroid"],
    ),
    # ── Transplant Medicine ───────────────────────────────────────────
    (
        "AST/ISHLT Solid Organ Transplant",
        "AST", 2024,
        "Post-Transplant Immunosuppression Maintenance",
        "Triple therapy with calcineurin inhibitor (tacrolimus preferred), antimetabolite (mycophenolate), and corticosteroids. Steroid withdrawal protocols considered after 3-6 months for low-risk kidney transplant recipients. Drug level monitoring essential for tacrolimus (target varies by transplant type and time post-transplant).",
        "A", "Strong",
        ["solid organ transplant", "immunosuppression"],
        ["tacrolimus", "mycophenolate mofetil", "prednisone", "basiliximab"],
        ["tacrolimus level", "serum creatinine", "donor-specific antibodies"],
        ["transplant", "immunosuppression", "tacrolimus", "rejection"],
    ),
    (
        "AST/IDSA Post-Transplant Infections",
        "AST/IDSA", 2024,
        "Infection Prophylaxis After Transplant",
        "CMV prophylaxis (valganciclovir) for D+/R- or high-risk recipients for 3-6 months. PJP prophylaxis (TMP-SMX) for 6-12 months. Hepatitis B prophylaxis if indicated. Annual influenza and pneumococcal vaccination. Avoid live vaccines while on immunosuppression.",
        "A", "Strong",
        ["transplant infection", "cmv", "pneumocystis"],
        ["valganciclovir", "trimethoprim-sulfamethoxazole"],
        ["cmv pcr", "ebv pcr", "bk virus pcr"],
        ["transplant infection", "cmv prophylaxis", "pjp", "immunosuppressed"],
    ),
    # ── Sleep Medicine ────────────────────────────────────────────────
    (
        "AASM Insomnia",
        "AASM", 2024,
        "Chronic Insomnia – CBT-I First-Line",
        "Cognitive behavioral therapy for insomnia (CBT-I) is recommended as first-line treatment over pharmacotherapy. CBT-I components: sleep restriction, stimulus control, cognitive restructuring, sleep hygiene, relaxation techniques. Digital CBT-I platforms are effective alternatives when in-person therapy is unavailable.",
        "A", "Strong",
        ["chronic insomnia", "insomnia disorder"],
        [],
        ["sleep diary", "actigraphy", "insomnia severity index"],
        ["insomnia", "cbt-i", "sleep restriction", "stimulus control"],
    ),
    (
        "AASM Restless Legs Syndrome",
        "AASM", 2024,
        "RLS Pharmacotherapy",
        "Iron supplementation if ferritin <75 ng/mL. Alpha-2-delta ligands (gabapentin enacarbil, pregabalin) are preferred first-line over dopamine agonists (DA augmentation risk). Low-dose DA (pramipexole, ropinirole) as alternative. Opioids (low-dose) for refractory cases. Avoid antihistamines and SSRIs which may worsen RLS.",
        "B", "Strong",
        ["restless legs syndrome", "willis-ekbom disease"],
        ["gabapentin enacarbil", "pregabalin", "pramipexole", "ropinirole", "iron"],
        ["serum ferritin", "iron studies", "polysomnography"],
        ["restless legs", "rls", "gabapentin", "dopamine agonist", "augmentation"],
    ),
    # ── Vascular Surgery – additional topics ──────────────────────────
    (
        "SVS Varicose Vein Guidelines",
        "SVS/AVF", 2024,
        "Varicose Vein Treatment",
        "Endovenous thermal ablation (laser or radiofrequency) is preferred over surgical stripping for great saphenous vein incompetence. Sclerotherapy for reticular and spider veins. Compression stockings for symptom management but not curative. Duplex ultrasound mapping before intervention.",
        "A", "Strong",
        ["varicose veins", "venous insufficiency"],
        [],
        ["duplex ultrasound venous", "ceap classification"],
        ["varicose veins", "endovenous ablation", "sclerotherapy", "saphenous"],
    ),
    (
        "SVS Aortic Dissection",
        "SVS/STS", 2024,
        "Acute Aortic Dissection Management",
        "Type A (ascending aorta): emergent surgical repair. Type B uncomplicated: medical management with IV beta-blockers targeting HR <60 and SBP <120. Complicated Type B (malperfusion, rupture, refractory pain/HTN): thoracic endovascular aortic repair (TEVAR). CT angiography is diagnostic imaging of choice.",
        "A", "Strong",
        ["aortic dissection", "acute aortic syndrome"],
        ["esmolol", "labetalol", "nicardipine"],
        ["cta aorta", "heart rate", "blood pressure"],
        ["aortic dissection", "type a", "type b", "tevar", "beta blocker"],
    ),
    # ── Sports Medicine ───────────────────────────────────────────────
    (
        "NCAA/AAN Concussion in Sport",
        "NCAA/AAN", 2024,
        "Sport-Related Concussion – Graduated Return",
        "Remove from play immediately upon suspicion. No return to sport same day. Graduated return-to-sport protocol: symptom-limited activity → light aerobic → sport-specific → non-contact drills → full contact → return to competition. Each stage minimum 24 hours. Neuropsychological testing may aid clinical decision-making.",
        "B", "Strong",
        ["concussion", "mild traumatic brain injury"],
        [],
        ["scat6", "neuropsychological testing", "balance testing"],
        ["concussion", "return to play", "graduated protocol", "sport"],
    ),
    (
        "ACSM Exercise-Related Heat Illness",
        "ACSM/NATA", 2024,
        "Exertional Heat Stroke Management",
        "Rectal temperature is gold standard (>40.5°C). Immediate cold water immersion (CWI) before transport; cool first, transport second. Target cooling to <39°C within 30 minutes. Do not administer antipyretics (ineffective for exertional heat stroke). Monitor for rhabdomyolysis, DIC, and organ failure.",
        "A", "Strong",
        ["heat stroke", "exertional heat illness"],
        [],
        ["rectal temperature", "ck", "coagulation studies", "renal function"],
        ["heat stroke", "cold water immersion", "exertional", "cooling"],
    ),
    # ── Addiction Medicine – additional topics ─────────────────────────
    (
        "ASAM Opioid Use Disorder",
        "ASAM", 2024,
        "OUD Medication-Assisted Treatment",
        "Buprenorphine or methadone are first-line MOUD for OUD. Buprenorphine can be initiated in office-based settings (X-waiver eliminated). Extended-release naltrexone is an alternative for patients who have achieved abstinence. MOUD should be offered indefinitely; no mandatory tapering timeline.",
        "A", "Strong",
        ["opioid use disorder", "opioid addiction"],
        ["buprenorphine", "methadone", "naltrexone extended-release"],
        ["urine drug screen", "cows score"],
        ["oud", "moud", "buprenorphine", "methadone", "naltrexone"],
    ),
    (
        "ASAM Stimulant Use Disorder",
        "ASAM", 2024,
        "Stimulant Use Disorder Management",
        "No FDA-approved pharmacotherapy for stimulant use disorder. Contingency management (motivational incentives) has strongest evidence. CBT and community reinforcement approach are effective. Mirtazapine and topiramate under investigation. Harm reduction approaches including naloxone distribution for polysubstance use.",
        "C", "Moderate",
        ["stimulant use disorder", "cocaine use disorder", "methamphetamine use disorder"],
        ["mirtazapine", "topiramate"],
        ["urine drug screen"],
        ["stimulant use disorder", "contingency management", "cocaine", "methamphetamine"],
    ),
    # ── Wound Care / Pressure Injury ──────────────────────────────────
    (
        "WHS Chronic Wound Management",
        "WHS", 2024,
        "Diabetic Foot Ulcer Management",
        "Offloading with total contact cast or irremovable knee-high device is gold standard for neuropathic plantar ulcers. Moist wound healing environment. Debridement of devitalized tissue. Assess for PAD (ABI/toe pressures). Revascularization for ischemic ulcers. Cellular and tissue-based products for stalled wounds.",
        "A", "Strong",
        ["diabetic foot ulcer", "neuropathic ulcer"],
        [],
        ["abi", "toe pressure", "wound measurement", "hba1c"],
        ["diabetic foot ulcer", "offloading", "total contact cast", "wound care"],
    ),
    (
        "WHS Venous Leg Ulcer",
        "WHS/SVS", 2024,
        "Venous Leg Ulcer Treatment",
        "Compression therapy (multicomponent bandaging or stockings providing 30-40 mmHg) is the foundation of treatment. Pentoxifylline as adjunct pharmacotherapy. Treat venous insufficiency with ablation when appropriate. Skin grafting for ulcers failing to heal after 4-6 weeks of standard care.",
        "A", "Strong",
        ["venous leg ulcer", "venous stasis ulcer"],
        ["pentoxifylline"],
        ["duplex ultrasound venous", "abi", "wound measurement"],
        ["venous ulcer", "compression therapy", "venous insufficiency"],
    ),
    # ── Urology – additional topics ───────────────────────────────────
    (
        "AUA Erectile Dysfunction",
        "AUA", 2024,
        "ED Assessment and Treatment",
        "Assess for modifiable risk factors (cardiovascular, metabolic, psychogenic). PDE5 inhibitors (sildenafil, tadalafil) are first-line pharmacotherapy. Vacuum erection devices as non-invasive alternative. Intracavernosal injection (alprostadil) for PDE5i non-responders. Penile prosthesis for refractory cases. Screen for cardiovascular risk.",
        "A", "Strong",
        ["erectile dysfunction", "impotence"],
        ["sildenafil", "tadalafil", "alprostadil"],
        ["testosterone level", "hba1c", "lipid panel"],
        ["erectile dysfunction", "pde5 inhibitor", "sildenafil", "cardiovascular risk"],
    ),
    (
        "AUA Male LUTS/BPH Advanced",
        "AUA", 2024,
        "BPH Surgical Options",
        "TURP remains gold standard for moderate-severe BPH. HoLEP/ThuLEP for large prostates (>80 mL). Minimally invasive options (UroLift, Rezum, Aquablation) for select patients wanting to preserve ejaculatory function. Simple prostatectomy (open/robotic) for very large prostates (>150 mL).",
        "A", "Strong",
        ["benign prostatic hyperplasia", "lower urinary tract symptoms"],
        ["tamsulosin", "finasteride"],
        ["psa", "uroflowmetry", "post-void residual", "prostate volume"],
        ["bph", "turp", "holep", "minimally invasive", "prostate"],
    ),
    # ── Obstetrics – additional topics ────────────────────────────────
    (
        "ACOG Preterm Labor",
        "ACOG", 2024,
        "Preterm Labor Management",
        "Antenatal corticosteroids (betamethasone 12 mg IM x2, 24h apart) for threatened preterm birth 24-34 weeks. Tocolysis (nifedipine or indomethacin <32 weeks) to allow steroid course completion. Magnesium sulfate for neuroprotection at <32 weeks. GBS prophylaxis if GBS status unknown.",
        "A", "Strong",
        ["preterm labor", "preterm birth"],
        ["betamethasone", "nifedipine", "indomethacin", "magnesium sulfate"],
        ["cervical length", "fetal fibronectin", "fetal heart rate"],
        ["preterm labor", "corticosteroids", "tocolysis", "neuroprotection"],
    ),
    (
        "ACOG Shoulder Dystocia",
        "ACOG", 2024,
        "Shoulder Dystocia Management",
        "Call for help immediately. Avoid fundal pressure. McRoberts maneuver + suprapubic pressure as initial steps. If unresolved: delivery of posterior arm, rotational maneuvers (Rubin II, Woods screw). Zavanelli maneuver as last resort. Document timing, maneuvers used, and neonatal status.",
        "B", "Strong",
        ["shoulder dystocia", "labor complication"],
        [],
        ["estimated fetal weight", "birth weight"],
        ["shoulder dystocia", "mcroberts", "suprapubic pressure", "delivery"],
    ),
    (
        "ACOG Ectopic Pregnancy",
        "ACOG", 2024,
        "Ectopic Pregnancy Management",
        "Methotrexate single-dose (50 mg/m2 IM) for unruptured ectopic with hCG <5000, no fetal cardiac activity, and ectopic <3.5 cm. Surgical management (salpingostomy or salpingectomy) for ruptured ectopic, hemodynamic instability, or methotrexate contraindication/failure. Serial hCG monitoring until undetectable.",
        "A", "Strong",
        ["ectopic pregnancy", "tubal pregnancy"],
        ["methotrexate"],
        ["beta-hcg", "transvaginal ultrasound"],
        ["ectopic pregnancy", "methotrexate", "salpingectomy", "hcg"],
    ),
    (
        "ACOG Gestational Diabetes",
        "ACOG", 2024,
        "GDM Glycemic Targets and Treatment",
        "Nutritional counseling and exercise first-line. Glucose targets: fasting <95, 1-hour postprandial <140, 2-hour <120 mg/dL. Insulin is preferred pharmacotherapy if lifestyle measures insufficient. Metformin and glyburide are alternatives if patient declines insulin. Antenatal testing from 32 weeks.",
        "A", "Strong",
        ["gestational diabetes", "gdm"],
        ["insulin", "metformin", "glyburide"],
        ["fasting glucose", "postprandial glucose", "hba1c"],
        ["gestational diabetes", "gdm", "insulin", "glucose targets"],
    ),
    # ── Psychiatry – additional topics ────────────────────────────────
    (
        "APA Obsessive-Compulsive Disorder",
        "APA", 2024,
        "OCD Treatment",
        "Exposure and response prevention (ERP) is first-line psychotherapy. SSRIs at higher doses than typical depression doses (e.g., fluoxetine 40-80 mg). Clomipramine as second-line or augmentation. SRI trial should last 8-12 weeks at adequate dose before declaring failure. Deep brain stimulation for severe refractory cases.",
        "A", "Strong",
        ["obsessive-compulsive disorder", "ocd"],
        ["fluoxetine", "fluvoxamine", "sertraline", "clomipramine"],
        ["y-bocs"],
        ["ocd", "erp", "ssri", "clomipramine"],
    ),
    (
        "APA ADHD in Adults",
        "APA/AACAP", 2024,
        "Adult ADHD Pharmacotherapy",
        "Stimulant medications (methylphenidate or amphetamine formulations) are first-line. Long-acting formulations preferred for consistent coverage. Non-stimulant alternatives: atomoxetine, viloxazine, guanfacine XR. Assess for coexisting conditions (anxiety, substance use) before stimulant initiation. Cardiovascular screening before starting stimulants.",
        "A", "Strong",
        ["attention deficit hyperactivity disorder", "adult adhd"],
        ["methylphenidate", "lisdexamfetamine", "atomoxetine", "viloxazine", "guanfacine"],
        ["blood pressure", "heart rate", "ecg"],
        ["adhd", "adult", "stimulant", "methylphenidate", "amphetamine"],
    ),
    (
        "APA Eating Disorders",
        "APA", 2024,
        "Bulimia Nervosa Treatment",
        "CBT-Enhanced (CBT-E) is first-line psychotherapy. Fluoxetine 60 mg is the only FDA-approved medication for bulimia nervosa. Guided self-help CBT as alternative for mild cases. Medical monitoring for electrolyte abnormalities (hypokalemia), dental erosion. Nutritional rehabilitation with structured meal plans.",
        "B", "Strong",
        ["bulimia nervosa", "eating disorder"],
        ["fluoxetine"],
        ["potassium", "bmp", "amylase", "dental exam"],
        ["bulimia", "eating disorder", "cbt", "fluoxetine"],
    ),
    (
        "APA Personality Disorders",
        "APA/NICE", 2024,
        "Borderline Personality Disorder Treatment",
        "Dialectical behavior therapy (DBT) is evidence-based psychotherapy for BPD. No medications are FDA-approved for BPD; pharmacotherapy targets specific symptoms (mood stabilizers for affective instability, low-dose antipsychotics for transient psychosis). Avoid long-term benzodiazepines. Crisis safety planning. Structured treatment framework.",
        "B", "Strong",
        ["borderline personality disorder", "bpd"],
        ["lamotrigine", "quetiapine"],
        [],
        ["bpd", "borderline", "dbt", "personality disorder"],
    ),
    # ── Critical Care – additional topics ─────────────────────────────
    (
        "SCCM ICU-Acquired Weakness",
        "SCCM", 2024,
        "ICU-Acquired Weakness Prevention",
        "Early mobilization and physical therapy within 24-48 hours of ICU admission (when safe) reduces ICU-acquired weakness. Minimize sedation (target light sedation). Avoid neuromuscular blocking agents when possible. Optimize nutrition. Electrical muscle stimulation is under investigation.",
        "B", "Moderate",
        ["icu-acquired weakness", "critical illness myopathy"],
        [],
        ["mrc sum score", "handgrip strength"],
        ["icu weakness", "early mobilization", "sedation minimization"],
    ),
    (
        "SCCM/ASPEN Nutrition in Critical Illness",
        "SCCM/ASPEN", 2024,
        "ICU Nutrition Protocol",
        "Initiate early enteral nutrition within 24-48 hours of ICU admission for hemodynamically stable patients. Trophic feeding initially, advance to goal over 48-72 hours. Protein target 1.2-2.0 g/kg/day. Parenteral nutrition if EN contraindicated or not meeting goals by day 7. Avoid overfeeding in early critical illness.",
        "A", "Strong",
        ["critical illness nutrition", "icu nutrition"],
        [],
        ["prealbumin", "nitrogen balance", "indirect calorimetry"],
        ["icu nutrition", "enteral nutrition", "protein", "trophic feeding"],
    ),
    (
        "SCCM Shock Management",
        "SCCM", 2024,
        "Vasopressor Selection in Shock",
        "Norepinephrine is first-line vasopressor for septic and distributive shock. Vasopressin (0.03-0.04 U/min) as adjunct to reduce norepinephrine dose. Epinephrine for refractory septic shock or anaphylaxis. Dobutamine for cardiogenic shock with low cardiac output. Phenylephrine avoided in septic shock except for pure vasoplegia.",
        "A", "Strong",
        ["shock", "vasopressor therapy"],
        ["norepinephrine", "vasopressin", "epinephrine", "dobutamine", "phenylephrine"],
        ["map", "central venous pressure", "lactate", "cardiac output"],
        ["vasopressor", "shock", "norepinephrine", "vasopressin"],
    ),
    # ── Genetic Medicine / Precision Medicine ─────────────────────────
    (
        "ACMG Pharmacogenomics",
        "ACMG/CPIC", 2024,
        "Pharmacogenomic Testing in Clinical Practice",
        "CYP2C19 testing recommended before clopidogrel initiation (poor metabolizers need alternative). CYP2D6 testing guides codeine, tramadol dosing (ultra-rapid metabolizers at risk). HLA-B*57:01 testing required before abacavir. DPYD testing recommended before fluoropyrimidine chemotherapy. TPMT/NUDT15 before thiopurines.",
        "A", "Strong",
        ["pharmacogenomics", "drug metabolism"],
        ["clopidogrel", "codeine", "abacavir", "fluorouracil", "azathioprine"],
        ["cyp2c19 genotype", "cyp2d6 genotype", "hla-b*57:01", "dpyd genotype"],
        ["pharmacogenomics", "cyp2c19", "precision medicine", "pgx"],
    ),
    (
        "ACMG Hereditary Cancer Syndromes",
        "ACMG/NCCN", 2024,
        "Li-Fraumeni Syndrome Surveillance",
        "TP53 carriers: annual whole-body MRI starting age 20 (or younger if childhood cancer history). Annual breast MRI for women starting age 20. Annual dermatologic exam. CBC and urinalysis every 3-4 months. Colonoscopy every 2-5 years starting age 25. Adrenal ultrasound for children.",
        "B", "Strong",
        ["li-fraumeni syndrome", "tp53 mutation"],
        [],
        ["whole-body mri", "breast mri", "cbc", "colonoscopy"],
        ["li-fraumeni", "tp53", "cancer predisposition", "surveillance"],
    ),
    # ── Palliative Care – additional topics ───────────────────────────
    (
        "NCCN Palliative Care Guidelines",
        "NCCN", 2025,
        "Palliative Care Pain Management Ladder",
        "WHO pain ladder: Step 1 non-opioid (acetaminophen, NSAIDs). Step 2 weak opioid (tramadol, codeine). Step 3 strong opioid (morphine, hydromorphone, fentanyl). Adjuvant agents (gabapentin, duloxetine) at each step. Breakthrough dosing: 10-15% of 24-hour opioid dose q1h PRN. Bowel regimen with all opioids.",
        "A", "Strong",
        ["cancer pain", "palliative pain management"],
        ["morphine", "hydromorphone", "fentanyl", "gabapentin", "duloxetine"],
        ["pain score", "functional status"],
        ["palliative pain", "who ladder", "opioid", "adjuvant"],
    ),
    (
        "AAHPM Goals of Care",
        "AAHPM", 2024,
        "Goals of Care Conversation Framework",
        "SPIKES protocol for serious illness communication. Assess patient understanding of illness. Explore values, goals, and fears. Align treatment plan with expressed goals. Document discussions in medical record. Update advance directives. Palliative care consultation for complex goals discussions.",
        "B", "Strong",
        ["goals of care", "advance care planning"],
        [],
        [],
        ["goals of care", "advance directive", "spikes", "serious illness"],
    ),
    # ── Nutrition / Metabolism ────────────────────────────────────────
    (
        "AACE Obesity Comprehensive",
        "AACE/Obesity Society", 2024,
        "Obesity Pharmacotherapy",
        "Anti-obesity medications (AOMs) recommended as adjunct to lifestyle for BMI ≥30 or ≥27 with comorbidities. Semaglutide 2.4 mg and tirzepatide show greatest weight loss efficacy (15-21%). Phentermine-topiramate, naltrexone-bupropion as alternatives. Long-term treatment typically required as weight regain common after discontinuation.",
        "A", "Strong",
        ["obesity", "weight management"],
        ["semaglutide", "tirzepatide", "phentermine-topiramate", "naltrexone-bupropion"],
        ["bmi", "waist circumference", "hba1c", "lipid panel"],
        ["obesity", "glp-1", "semaglutide", "tirzepatide", "weight loss"],
    ),
    (
        "ASPEN Parenteral Nutrition",
        "ASPEN", 2024,
        "Adult Parenteral Nutrition Management",
        "PN indicated when EN is contraindicated or insufficient for >7 days (or >3 days in malnourished patients). Start with moderate caloric goals (20-25 kcal/kg/day). Protein 1.5-2.0 g/kg/day for critically ill. Monitor electrolytes daily initially, then weekly. Refeeding syndrome prevention with thiamine and phosphate monitoring.",
        "A", "Strong",
        ["parenteral nutrition", "malnutrition"],
        ["thiamine"],
        ["phosphate", "magnesium", "potassium", "triglycerides", "liver function tests"],
        ["parenteral nutrition", "tpn", "refeeding syndrome", "malnutrition"],
    ),
    # ── Miscellaneous remaining gaps ──────────────────────────────────
    (
        "CFF Cystic Fibrosis Guidelines",
        "CFF", 2024,
        "CF CFTR Modulator Therapy",
        "Elexacaftor/tezacaftor/ivacaftor (Trikafta) is recommended for patients ≥2 years with at least one F508del mutation (~90% of CF patients). Significant improvements in FEV1, sweat chloride, and quality of life. Continue airway clearance and other CF therapies. Monitor liver function and cataracts.",
        "A", "Strong",
        ["cystic fibrosis"],
        ["elexacaftor-tezacaftor-ivacaftor", "ivacaftor"],
        ["fev1", "sweat chloride", "sputum culture"],
        ["cystic fibrosis", "cftr modulator", "trikafta", "f508del"],
    ),
    (
        "NASS Lumbar Spinal Stenosis",
        "NASS", 2024,
        "Lumbar Spinal Stenosis Treatment",
        "Initial management with physical therapy, NSAIDs, and activity modification. Epidural steroid injections for short-term symptom relief. Surgical decompression (laminectomy) for patients with severe neurogenic claudication failing conservative management. Fusion reserved for concurrent instability.",
        "B", "Moderate",
        ["lumbar spinal stenosis", "neurogenic claudication"],
        ["naproxen", "gabapentin", "methylprednisolone"],
        ["mri lumbar spine", "walking distance", "oswestry disability index"],
        ["spinal stenosis", "neurogenic claudication", "laminectomy", "decompression"],
    ),
    (
        "AAN Spasticity Management",
        "AAN", 2024,
        "Spasticity Treatment",
        "Physical therapy and stretching are foundation of management. Oral baclofen, tizanidine, or dantrolene for generalized spasticity. Botulinum toxin injection for focal/regional spasticity. Intrathecal baclofen pump for severe generalized spasticity refractory to oral medications.",
        "B", "Strong",
        ["spasticity", "upper motor neuron syndrome"],
        ["baclofen", "tizanidine", "dantrolene", "botulinum toxin"],
        ["modified ashworth scale", "rom assessment"],
        ["spasticity", "baclofen", "botulinum toxin", "intrathecal"],
    ),
    (
        "ESHRE/ASRM Endometriosis",
        "ESHRE/ASRM", 2024,
        "Endometriosis Management",
        "NSAIDs for pain. Combined OCPs or progestins as first-line hormonal therapy. GnRH agonists with add-back therapy for refractory cases. Dienogest or elagolix as newer options. Laparoscopic excision/ablation for surgical management. Fertility preservation counseling. Endometriomas >4 cm: consider surgical excision before ART.",
        "B", "Strong",
        ["endometriosis", "dysmenorrhea", "chronic pelvic pain"],
        ["combined oral contraceptives", "dienogest", "elagolix", "leuprolide"],
        ["pelvic ultrasound", "mri pelvis", "ca-125"],
        ["endometriosis", "hormonal therapy", "laparoscopy", "dysmenorrhea"],
    ),
    (
        "ESC Pericardial Disease",
        "ESC", 2024,
        "Cardiac Tamponade",
        "Emergent pericardiocentesis for hemodynamically significant tamponade. Echo-guided approach preferred. IV fluid bolus as temporizing measure. Avoid diuretics and vasodilators (reduce preload). Surgical pericardial window for recurrent effusions. Drain management and fluid analysis (cytology, culture, protein, LDH).",
        "A", "Strong",
        ["cardiac tamponade", "pericardial effusion"],
        [],
        ["echocardiogram", "pericardial fluid analysis", "blood pressure"],
        ["cardiac tamponade", "pericardiocentesis", "pericardial effusion"],
    ),
    (
        "NICE/AAN Chronic Headache Guidelines",
        "AAN/AHS", 2024,
        "Migraine Acute Treatment",
        "NSAIDs or triptans as first-line for moderate-severe migraine attacks. Treat early in the attack for best efficacy. Gepants (ubrogepant, rimegepant) for patients who cannot use triptans. Ditans (lasmiditan) as alternative. Antiemetics (metoclopramide) as adjunct. Limit acute medication use to <10-15 days/month to prevent MOH.",
        "A", "Strong",
        ["migraine", "acute headache"],
        ["sumatriptan", "ibuprofen", "ubrogepant", "rimegepant", "lasmiditan", "metoclopramide"],
        ["headache diary", "midas score"],
        ["migraine", "acute treatment", "triptan", "gepant"],
    ),
    (
        "AHS/AAN CGRP Migraine Prevention",
        "AHS/AAN", 2024,
        "CGRP Monoclonal Antibodies for Migraine Prevention",
        "CGRP mAbs (erenumab, fremanezumab, galcanezumab, eptinezumab) are effective for episodic and chronic migraine prevention. Generally well-tolerated; constipation and injection site reactions most common. Consider for patients who have failed or cannot tolerate 2+ oral preventives. Eptinezumab is IV; others are SC self-injection.",
        "A", "Strong",
        ["chronic migraine", "migraine prevention"],
        ["erenumab", "fremanezumab", "galcanezumab", "eptinezumab"],
        ["monthly migraine days", "headache impact test"],
        ["cgrp", "migraine prevention", "monoclonal antibody", "erenumab"],
    ),
    (
        "ACS Colorectal Cancer Screening",
        "ACS/MSTF", 2024,
        "CRC Screening Modalities",
        "Average-risk adults: begin screening at age 45. Colonoscopy every 10 years (preferred), or stool-based tests (FIT annually, mt-sDNA every 3 years). CT colonography every 5 years as alternative. High-risk (family history, prior polyps): colonoscopy at earlier age with shorter intervals per guidelines.",
        "A", "Strong",
        ["colorectal cancer screening", "colon cancer"],
        [],
        ["colonoscopy", "fit", "mt-sdna", "ct colonography"],
        ["colorectal cancer screening", "colonoscopy", "fit", "cologuard"],
    ),
    (
        "HRS Cardiac Arrhythmia Guidelines",
        "HRS", 2024,
        "Ventricular Tachycardia Management",
        "Hemodynamically unstable VT: immediate synchronized cardioversion. Stable monomorphic VT: IV amiodarone or procainamide. Catheter ablation for recurrent VT. ICD for secondary prevention after sustained VT/VF not due to reversible cause. Substrate-based ablation for VT storm. Avoid Class IC antiarrhythmics in structural heart disease.",
        "A", "Strong",
        ["ventricular tachycardia", "ventricular fibrillation"],
        ["amiodarone", "procainamide", "lidocaine"],
        ["12-lead ecg", "echocardiogram", "electrophysiology study"],
        ["ventricular tachycardia", "icd", "catheter ablation", "antiarrhythmic"],
    ),
    # ── Additional specialties filling to ~160 ────────────────────────
    (
        "NCCN Sarcoma Guidelines",
        "NCCN", 2025,
        "Soft Tissue Sarcoma Treatment",
        "Wide local excision with adequate margins is standard surgical approach. Radiation therapy recommended for high-grade or margin-close tumors. Doxorubicin-based chemotherapy for advanced/metastatic disease. Trabectedin for liposarcoma/leiomyosarcoma after anthracycline failure. Multidisciplinary tumor board review essential.",
        "B", "Strong",
        ["soft tissue sarcoma"],
        ["doxorubicin", "ifosfamide", "trabectedin", "pazopanib"],
        ["mri", "ct chest", "biopsy"],
        ["sarcoma", "soft tissue", "doxorubicin", "wide excision"],
    ),
    (
        "NCCN CNS Tumors",
        "NCCN", 2025,
        "Glioblastoma Standard of Care",
        "Maximal safe resection followed by concurrent temozolomide + radiation (Stupp protocol). MGMT methylation status guides treatment decisions (predictive for temozolomide benefit). Bevacizumab for recurrent GBM. Tumor treating fields (TTFields) as adjunct. Dexamethasone for cerebral edema. Seizure prophylaxis only if seizures occur.",
        "A", "Strong",
        ["glioblastoma", "high-grade glioma"],
        ["temozolomide", "bevacizumab", "dexamethasone", "levetiracetam"],
        ["brain mri", "mgmt methylation", "idh mutation"],
        ["glioblastoma", "gbm", "temozolomide", "stupp protocol"],
    ),
    (
        "NCCN Testicular Cancer",
        "NCCN", 2025,
        "Testicular Cancer Management",
        "Radical inguinal orchiectomy for diagnosis and initial treatment. Stage I seminoma: surveillance vs. single-agent carboplatin vs. radiation. Stage I non-seminoma: surveillance vs. RPLND vs. BEP x1 cycle. Sperm banking before treatment. Tumor markers (AFP, beta-hCG, LDH) for staging and monitoring.",
        "A", "Strong",
        ["testicular cancer", "seminoma", "non-seminoma germ cell tumor"],
        ["cisplatin", "etoposide", "bleomycin", "carboplatin"],
        ["afp", "beta-hcg", "ldh", "ct abdomen pelvis"],
        ["testicular cancer", "seminoma", "bep", "orchiectomy"],
    ),
    (
        "NCCN Cervical Cancer Guidelines",
        "NCCN", 2025,
        "Cervical Cancer Treatment",
        "Early stage (IA1-IB1): cone biopsy or simple hysterectomy. Stage IB2-IVA: concurrent chemoradiation with cisplatin. Pembrolizumab added for PD-L1+ advanced/recurrent disease. Bevacizumab added to chemotherapy for persistent/recurrent disease. HPV vaccination for primary prevention.",
        "A", "Strong",
        ["cervical cancer", "cervical dysplasia"],
        ["cisplatin", "pembrolizumab", "bevacizumab", "paclitaxel"],
        ["pap smear", "hpv test", "pet-ct", "mri pelvis"],
        ["cervical cancer", "chemoradiation", "cisplatin", "hpv"],
    ),
    (
        "NCCN Esophageal Cancer Guidelines",
        "NCCN", 2025,
        "Esophageal Cancer Treatment",
        "Endoscopic resection for superficial tumors (T1a). Neoadjuvant chemoradiation (CROSS regimen) followed by esophagectomy for locally advanced disease. Nivolumab adjuvant for residual disease after neoadjuvant chemoRT. Pembrolizumab + chemotherapy for advanced/metastatic (PD-L1 CPS ≥5).",
        "A", "Strong",
        ["esophageal cancer", "esophageal adenocarcinoma", "esophageal squamous cell carcinoma"],
        ["carboplatin", "paclitaxel", "nivolumab", "pembrolizumab"],
        ["egd", "eus", "pet-ct"],
        ["esophageal cancer", "cross protocol", "esophagectomy", "immunotherapy"],
    ),
    (
        "KDIGO CKD-MBD Guidelines",
        "KDIGO", 2024,
        "CKD-Mineral Bone Disorder Management",
        "Maintain phosphate within normal range using dietary restriction and phosphate binders. Avoid calcium-based binders in dialysis patients with hypercalcemia or adynamic bone. Active vitamin D for CKD G3-G5D with secondary hyperparathyroidism. Cinacalcet for persistent hyperparathyroidism on dialysis. PTH target 2-9x upper normal for dialysis patients.",
        "B", "Strong",
        ["ckd-mbd", "secondary hyperparathyroidism", "renal osteodystrophy"],
        ["sevelamer", "lanthanum", "calcitriol", "paricalcitol", "cinacalcet"],
        ["pth", "calcium", "phosphate", "25-oh vitamin d", "alkaline phosphatase"],
        ["ckd-mbd", "phosphate binder", "secondary hyperparathyroidism", "pth"],
    ),
    (
        "KDIGO Hypertension in CKD",
        "KDIGO", 2024,
        "BP Targets in CKD",
        "Target systolic BP <120 mmHg (standardized office measurement) for most CKD patients. ACE inhibitors or ARBs first-line, especially with albuminuria. Finerenone (non-steroidal MRA) for CKD with T2DM and albuminuria to reduce kidney and cardiovascular events. Thiazide-like diuretics effective in CKD G1-G3; loop diuretics for G4-G5.",
        "A", "Strong",
        ["hypertension", "chronic kidney disease"],
        ["lisinopril", "losartan", "finerenone", "chlorthalidone", "furosemide"],
        ["blood pressure", "uacr", "egfr", "potassium"],
        ["ckd hypertension", "raas blockade", "finerenone", "bp target"],
    ),
    (
        "ACC/AHA Heart Failure with Preserved EF",
        "ACC/AHA", 2024,
        "HFpEF Comprehensive Management",
        "SGLT2 inhibitors (empagliflozin, dapagliflozin) reduce HF hospitalizations in HFpEF. Diuretics for volume management. Treat comorbidities (AF, hypertension, obesity, coronary disease). GLP-1 RAs for HFpEF with obesity. MRAs (spironolactone) may reduce hospitalizations. Exercise rehabilitation improves functional capacity.",
        "A", "Strong",
        ["heart failure with preserved ejection fraction", "hfpef", "diastolic heart failure"],
        ["empagliflozin", "dapagliflozin", "spironolactone", "furosemide", "semaglutide"],
        ["nt-probnp", "echocardiogram", "6-minute walk test"],
        ["hfpef", "sglt2 inhibitor", "diastolic heart failure", "preserved ef"],
    ),
    (
        "ADA/EASD T2DM Comprehensive Algorithm",
        "ADA/EASD", 2024,
        "T2DM Cardiorenal Protective Therapy",
        "SGLT2 inhibitors for T2DM with established CKD (eGFR ≥20), heart failure, or high cardiovascular risk regardless of HbA1c. GLP-1 RAs for T2DM with established ASCVD or high cardiovascular risk. Finerenone for T2DM with CKD and albuminuria. Metformin remains first-line for glycemic management. Dual GLP-1/GIP agonist (tirzepatide) for additional glycemic and weight benefit.",
        "A", "Strong",
        ["type 2 diabetes", "diabetic kidney disease", "cardiovascular disease"],
        ["metformin", "empagliflozin", "dapagliflozin", "semaglutide", "tirzepatide", "finerenone"],
        ["hba1c", "egfr", "uacr", "nt-probnp"],
        ["t2dm", "sglt2", "glp-1", "cardiorenal", "finerenone"],
    ),
]

def main():
    fixture_path = os.path.join(os.path.dirname(__file__), "..", "fixtures", "clinical_guidelines.json")
    with open(fixture_path) as f:
        data = json.load(f)

    existing_ids = {s["section_id"] for s in data["guidelines"]}
    added = 0

    for entry in SECTIONS:
        guideline, society, year, title, text, grade, strength, conditions, meds, measurements, keywords = entry
        sid = _id(guideline, title)
        if sid in existing_ids:
            continue
        existing_ids.add(sid)
        data["guidelines"].append({
            "section_id": sid,
            "guideline": f"{guideline} ({year})",
            "section_title": title,
            "recommendation_text": text,
            "evidence_grade": grade,
            "recommendation_level": strength,
            "source_society": society,
            "applies_to_conditions": conditions,
            "applies_to_medications": meds,
            "applies_to_measurements": measurements,
            "keywords": keywords,
        })
        added += 1

    with open(fixture_path, "w") as f:
        json.dump(data, f, indent=2)

    total = len(data["guidelines"])
    print(f"Batch 11: added {added} sections (total now {total})")


if __name__ == "__main__":
    main()
