"""Services for Clinical Ontology Normalizer.

Services implement business logic and data processing:
- VocabularyService: OMOP concept lookup and matching (task 2.7)
- NLPService: Mention extraction (task 4.x)
- MappingService: OMOP concept mapping (task 5.x)
- FactBuilderService: ClinicalFact construction (task 6.x)
- GraphBuilderService: Knowledge graph materialization (task 7.x)
- OMOPExporter: Export to OMOP CDM format (task 9.x)
"""

from app.services.export import (
    BaseOMOPExporter,
    DatabaseOMOPExporter,
    NoteExport,
    NoteNLPExport,
    OMOPExportResult,
)
from app.services.fact_builder import (
    BaseFactBuilderService,
    EvidenceInput,
    FactBuilderServiceInterface,
    FactInput,
    FactResult,
)
from app.services.fact_builder_db import DatabaseFactBuilderService
from app.services.graph_builder import (
    BaseGraphBuilderService,
    EdgeInput,
    GraphBuilderServiceInterface,
    GraphResult,
    NodeInput,
)
from app.services.graph_builder_db import DatabaseGraphBuilderService
from app.services.mapping import (
    BaseMappingService,
    ConceptCandidate,
    MappingMethod,
    MappingServiceInterface,
)
from app.services.mapping_db import DatabaseMappingService
from app.services.mapping_sql import SQLMappingService
from app.services.nlp_vocabulary import FilteredNLPVocabularyService
from app.services.nlp import BaseNLPService, ExtractedMention, NLPServiceInterface
from app.services.nlp_rule_based import RuleBasedNLPService
from app.services.value_extraction import (
    ExtractedValue,
    ValueExtractionService,
    get_value_extraction_service,
)
from app.services.vocabulary import (
    VocabularyService,
    get_vocabulary_service,
    preload_vocabulary,
    reset_vocabulary_singleton,
)
from app.services.nlp_clinical_ner import (
    ClinicalNERService,
    TransformerNERConfig,
    get_clinical_ner_service,
    reset_clinical_ner_service,
)
from app.services.relation_extraction import (
    ExtractedRelation,
    RelationExtractionConfig,
    RelationExtractionService,
    RelationType,
    get_relation_extraction_service,
    reset_relation_extraction_service,
)
from app.services.nlp_ensemble import (
    EnsembleConfig,
    EnsembleNLPService,
    EnsembleResult,
    get_ensemble_nlp_service,
    reset_ensemble_nlp_service,
)
from app.services.vocabulary_enhanced import (
    EnhancedVocabularyService,
    get_enhanced_vocabulary_service,
    reset_enhanced_vocabulary_service,
    ABBREVIATION_EXPANSIONS,
    SYNONYM_PATTERNS,
)
from app.services.drug_interactions import (
    DrugInteraction,
    DrugInteractionService,
    InteractionCheckResult,
    InteractionSeverity,
    InteractionType,
    get_drug_interaction_service,
    reset_drug_interaction_service,
)
from app.services.lab_reference import (
    InterpretationLevel,
    LabCategory,
    LabInterpretation,
    LabReferenceService,
    ReferenceRange,
    get_lab_reference_service,
    reset_lab_reference_service,
)
from app.services.clinical_calculators import (
    CalculatorResult,
    ClinicalCalculatorService,
    RiskLevel,
    get_clinical_calculator_service,
    reset_clinical_calculator_service,
)
from app.services.differential_diagnosis import (
    ClinicalDomain,
    DiagnosisCandidate,
    DiagnosisUrgency,
    DifferentialDiagnosisService,
    DifferentialResult,
    get_differential_diagnosis_service,
    reset_differential_diagnosis_service,
)
from app.services.drug_safety import (
    DrugSafetyProfile,
    DrugSafetyService,
    LactationSafety,
    PregnancyCategory,
    SafetyCheckResult,
    SafetyLevel,
    get_drug_safety_service,
    reset_drug_safety_service,
)
from app.services.icd10_suggester import (
    CERCitation as ICD10CERCitation,
    CodeCategory,
    CodeConfidence,
    CodeSuggestion,
    ICD10Code,
    ICD10SuggesterService,
    SuggestionResult,
    get_icd10_suggester_service,
    reset_icd10_suggester_service,
)
from app.services.differential_diagnosis import (
    CERStrength,
    DiagnosisCERCitation,
)
from app.services.cpt_suggester import (
    CERCitation as CPTCERCitation,
    ConfidenceLevel,
    CPTCategory,
    CPTCode,
    CPTSuggesterService,
    CPTSuggestion,
    CPTSuggestionResult,
    DocumentationRequirement,
    ServicePlace,
    get_cpt_suggester_service,
    reset_cpt_suggester_service,
)
from app.services.billing_optimizer import (
    BillingCERCitation,
    BillingOptimizationResult,
    BillingOptimizationService,
    ConfidenceLevel as BillingConfidenceLevel,
    EncounterCodes,
    EncounterContext,
    OptimizationCategory,
    OptimizationFinding,
    SeverityLevel,
    get_billing_optimization_service,
    reset_billing_optimization_service,
)
from app.services.enhanced_extraction import (
    EnhancedExtractionService,
    EntityDeduplicator,
    EntityNormalizer,
    ExtractionCache,
    ExtractedEntity as EnhancedExtractedEntity,
    ExtractionResult as EnhancedExtractionResult,
    get_enhanced_extraction_service,
    reset_enhanced_extraction_service,
    with_retry,
)
from app.services.coding_query_generator import (
    CERCitation as QueryCERCitation,
    CodingImpact,
    CodingQuery,
    CodingQueryGeneratorService,
    QueryBatch,
    QueryPriority,
    QueryStatus,
    ResponseOption,
    get_coding_query_generator_service,
    reset_coding_query_generator_service,
)
from app.services.hcc_analyzer import (
    CaptureConfidence,
    GapType,
    HCCAnalysisResult,
    HCCAnalyzerService,
    HCCCategory,
    HCCDefinition,
    HCCEvidence,
    HCCOpportunity,
    get_hcc_analyzer_service,
    reset_hcc_analyzer_service,
)
from app.services.nlp_advanced import (
    AbbreviationContext,
    AdvancedNLPConfig,
    AdvancedNLPService,
    EnhancedMention,
    Laterality,
    MentionEnhancement,
    get_advanced_nlp_service,
    reset_advanced_nlp_service,
)
from app.services.vocabulary_mapping import (
    BatchMappingResult,
    ConfidenceLevel as MappingConfidenceLevel,
    LocalCodeMapping,
    MappingResult,
    MappingType,
    SourceVocabulary,
    TargetVocabulary,
    VocabularyMappingService,
    get_vocabulary_mapping_service,
    reset_vocabulary_mapping_service,
)
from app.services.event_stream import (
    EventStreamService,
    EventType,
    ProcessingEvent,
    get_event_stream_service,
    reset_event_stream_service,
    publish_extraction_started,
    publish_mention_found,
    publish_extraction_complete,
    publish_processing_complete,
    publish_error,
    publish_job_started,
    publish_job_progress,
    publish_job_complete,
)
from app.services.rxnorm_service import (
    DrugClassLookupResult,
    DrugInfo,
    DrugIngredient,
    DrugLookupResult,
    DrugMatchType,
    NDCLookupResult,
    RxNormService,
    RxNormTermType,
    get_rxnorm_service,
    reset_rxnorm_service,
)
from app.services.snomed_service import (
    ConceptMatch,
    CrossMapResult,
    HierarchyResult,
    MatchConfidence,
    SemanticType,
    SNOMEDConcept,
    SNOMEDService,
    get_snomed_service,
    reset_snomed_service,
)
from app.services.llm_service import (
    CostEstimate,
    LLMConfig,
    LLMMessage,
    LLMModel,
    LLMProvider,
    LLMResponse,
    LLMService,
    TokenUsage,
    estimate_cost,
    estimate_tokens,
    get_llm_service,
    reset_llm_service,
)
from app.services.llm_summarizer import (
    AssessmentPlanItem,
    AssessmentPlanResult,
    ClinicalSection,
    ClinicalSummarizerLLM,
    ClinicalSummaryResult,
    DischargeSummaryResult,
    EncounterData,
    KeyFinding,
    KeyFindingsResult,
    SummaryLength,
    get_clinical_summarizer_llm,
    reset_clinical_summarizer_llm,
)
from app.services.calculator_builder import (
    CalculatorBuilderService,
    CalculatorExecutionResult,
    CalculatorInputDefinition,
    FormulaValidationResult,
    get_calculator_builder_service,
    reset_calculator_builder_service,
)
from app.services.smart_fhir import (
    AuthorizationError as SMARTAuthorizationError,
    FHIRRequestError,
    LaunchContext,
    OAuthState,
    SMARTClient,
    SMARTClientError,
    TokenError,
    TokenSet,
    TokenType,
    get_smart_client,
    reset_smart_client,
)
from app.services.medication_reconciliation import (
    DiscrepancyAlert,
    DiscrepancySeverity,
    DiscrepancyType,
    MedicationEntry,
    MedicationListAnalysis,
    MedicationMatch,
    MedicationReconciliationService,
    MedicationRoute,
    ReconciliationResult,
    ReconciliationStatus,
    TherapeuticDuplicate,
    get_medication_reconciliation_service,
    reset_medication_reconciliation_service,
)
from app.services.note_generator import (
    ClinicalNoteGeneratorService,
    ConfidenceLevel as NoteConfidenceLevel,
    EncounterData as NoteEncounterData,
    GeneratedNote,
    NoteEnhancementResult,
    NoteGenerationRequest,
    NoteSection,
    NoteSectionTemplate,
    NoteStatus,
    NoteTemplate,
    NoteType,
    NoteValidationResult,
    PatientData,
    SectionStatus,
    get_note_generator_service,
    reset_note_generator_service,
)
from app.services.quality_measures import (
    AgeRange,
    AgeUnit,
    ComplianceStatus,
    EligibilityCriteria,
    MeasureCategory,
    MeasurePerformance,
    MeasurePriority,
    MeasureResult,
    MeasureType,
    NumeratorCriteria,
    PatientEvaluationResult,
    PatientGap,
    PerformanceReport,
    QualityMeasure,
    QualityMeasureService,
    get_quality_measure_service,
    reset_quality_measure_service,
)
from app.services.patient_timeline import (
    CareGap,
    EventSeverity,
    GapAnalysisResult,
    GapPriority,
    GapType,
    PatientTimeline,
    PatientTimelineService,
    TimelineEvent,
    TimelineEventType,
    TimelineFilter,
    TimelineSummary,
    get_patient_timeline_service,
    reset_patient_timeline_service,
)
from app.services.data_quality_service import (
    DataQualityService,
    DQDCategory,
    DQDCategorySummary,
    DQDCheckDefinition,
    DQDCheckResult,
    DQDHistoryEntry,
    DQDIssue,
    DQDRunResult,
    DQDSeverity,
    DQDStatus,
    DQDSubcategory,
    DQDSummary,
    DQDTableSummary,
    OMOPTable,
    get_data_quality_service,
    reset_data_quality_service,
)
from app.services.value_set_service import (
    FilterOperator,
    InclusionRule,
    InclusionRuleType,
    ValidationResult,
    ValueSet,
    ValueSetCode,
    ValueSetExpansionResult,
    ValueSetService,
    ValueSetStatus,
    ValueSetType,
    ValueSetVersion,
    get_value_set_service,
    reset_value_set_service,
)
from app.services.synthetic_data_service import (
    AgeDistribution,
    ConditionPrevalence,
    FHIRBundle,
    GenderDistribution,
    GenerationJob,
    GenerationTemplate,
    JobStatus as SyntheticJobStatus,
    LabCorrelation,
    MedicationPattern,
    OutputFormat,
    PrivacyConfig,
    PrivacyReport,
    RaceDistribution,
    SynthesisConfig,
    SyntheticDataService,
    SyntheticPatient,
    ValidationReport,
    get_synthetic_data_service,
    reset_synthetic_data_service,
)
from app.services.tefca_service import (
    AuditEventType as TEFCAAuditEventType,
    AuditLog as TEFCAAuditLog,
    ClinicalDocument as TEFCAClinicalDocument,
    ConsentStatus as TEFCAConsentStatus,
    DirectMessage,
    DirectMessageStatus,
    DocumentClass,
    DocumentQueryResponse,
    DocumentReference as TEFCADocumentReference,
    ExchangePurpose,
    MatchConfidence as TEFCAMatchConfidence,
    PatientConsent,
    PatientDemographics,
    PatientMatch,
    QHIN,
    QHINStatus,
    QueryResponse,
    SendResult,
    TEFCAQuery,
    TEFCAService,
    ValidationResult as TEFCAValidationResult,
    get_tefca_service,
    reset_tefca_service,
)

__all__ = [
    "BaseFactBuilderService",
    "BaseGraphBuilderService",
    "BaseMappingService",
    "BaseNLPService",
    "ConceptCandidate",
    "DatabaseFactBuilderService",
    "DatabaseGraphBuilderService",
    "DatabaseMappingService",
    "EdgeInput",
    "EvidenceInput",
    "ExtractedMention",
    "FactBuilderServiceInterface",
    "FactInput",
    "FactResult",
    "FilteredNLPVocabularyService",
    "GraphBuilderServiceInterface",
    "GraphResult",
    "MappingMethod",
    "MappingServiceInterface",
    "NodeInput",
    "NLPServiceInterface",
    "RuleBasedNLPService",
    "SQLMappingService",
    "VocabularyService",
    "get_vocabulary_service",
    "preload_vocabulary",
    "reset_vocabulary_singleton",
    "BaseOMOPExporter",
    "DatabaseOMOPExporter",
    "NoteExport",
    "NoteNLPExport",
    "OMOPExportResult",
    "ExtractedValue",
    "ValueExtractionService",
    "get_value_extraction_service",
    "ClinicalNERService",
    "TransformerNERConfig",
    "get_clinical_ner_service",
    "reset_clinical_ner_service",
    "ExtractedRelation",
    "RelationExtractionConfig",
    "RelationExtractionService",
    "RelationType",
    "get_relation_extraction_service",
    "reset_relation_extraction_service",
    "EnsembleConfig",
    "EnsembleNLPService",
    "EnsembleResult",
    "get_ensemble_nlp_service",
    "reset_ensemble_nlp_service",
    "EnhancedVocabularyService",
    "get_enhanced_vocabulary_service",
    "reset_enhanced_vocabulary_service",
    "ABBREVIATION_EXPANSIONS",
    "SYNONYM_PATTERNS",
    "DrugInteraction",
    "DrugInteractionService",
    "InteractionCheckResult",
    "InteractionSeverity",
    "InteractionType",
    "get_drug_interaction_service",
    "reset_drug_interaction_service",
    "InterpretationLevel",
    "LabCategory",
    "LabInterpretation",
    "LabReferenceService",
    "ReferenceRange",
    "get_lab_reference_service",
    "reset_lab_reference_service",
    "CalculatorResult",
    "ClinicalCalculatorService",
    "RiskLevel",
    "get_clinical_calculator_service",
    "reset_clinical_calculator_service",
    "ClinicalDomain",
    "DiagnosisCandidate",
    "DiagnosisUrgency",
    "DifferentialDiagnosisService",
    "DifferentialResult",
    "get_differential_diagnosis_service",
    "reset_differential_diagnosis_service",
    "DrugSafetyProfile",
    "DrugSafetyService",
    "LactationSafety",
    "PregnancyCategory",
    "SafetyCheckResult",
    "SafetyLevel",
    "get_drug_safety_service",
    "reset_drug_safety_service",
    "CodeCategory",
    "CodeConfidence",
    "CodeSuggestion",
    "ICD10Code",
    "ICD10SuggesterService",
    "SuggestionResult",
    "get_icd10_suggester_service",
    "reset_icd10_suggester_service",
    "ICD10CERCitation",
    "CERStrength",
    "DiagnosisCERCitation",
    "CPTCERCitation",
    "ConfidenceLevel",
    "CPTCategory",
    "CPTCode",
    "CPTSuggesterService",
    "CPTSuggestion",
    "CPTSuggestionResult",
    "DocumentationRequirement",
    "ServicePlace",
    "get_cpt_suggester_service",
    "reset_cpt_suggester_service",
    "BillingCERCitation",
    "BillingOptimizationResult",
    "BillingOptimizationService",
    "BillingConfidenceLevel",
    "EncounterCodes",
    "EncounterContext",
    "OptimizationCategory",
    "OptimizationFinding",
    "SeverityLevel",
    "get_billing_optimization_service",
    "reset_billing_optimization_service",
    "EnhancedExtractionService",
    "EntityDeduplicator",
    "EntityNormalizer",
    "ExtractionCache",
    "EnhancedExtractedEntity",
    "EnhancedExtractionResult",
    "get_enhanced_extraction_service",
    "reset_enhanced_extraction_service",
    "with_retry",
    "QueryCERCitation",
    "CodingImpact",
    "CodingQuery",
    "CodingQueryGeneratorService",
    "QueryBatch",
    "QueryPriority",
    "QueryStatus",
    "ResponseOption",
    "get_coding_query_generator_service",
    "reset_coding_query_generator_service",
    "CaptureConfidence",
    "GapType",
    "HCCAnalysisResult",
    "HCCAnalyzerService",
    "HCCCategory",
    "HCCDefinition",
    "HCCEvidence",
    "HCCOpportunity",
    "get_hcc_analyzer_service",
    "reset_hcc_analyzer_service",
    "AbbreviationContext",
    "AdvancedNLPConfig",
    "AdvancedNLPService",
    "EnhancedMention",
    "Laterality",
    "MentionEnhancement",
    "get_advanced_nlp_service",
    "reset_advanced_nlp_service",
    "BatchMappingResult",
    "MappingConfidenceLevel",
    "LocalCodeMapping",
    "MappingResult",
    "MappingType",
    "SourceVocabulary",
    "TargetVocabulary",
    "VocabularyMappingService",
    "get_vocabulary_mapping_service",
    "reset_vocabulary_mapping_service",
    "EventStreamService",
    "EventType",
    "ProcessingEvent",
    "get_event_stream_service",
    "reset_event_stream_service",
    "publish_extraction_started",
    "publish_mention_found",
    "publish_extraction_complete",
    "publish_processing_complete",
    "publish_error",
    "publish_job_started",
    "publish_job_progress",
    "publish_job_complete",
    "DrugClassLookupResult",
    "DrugInfo",
    "DrugIngredient",
    "DrugLookupResult",
    "DrugMatchType",
    "NDCLookupResult",
    "RxNormService",
    "RxNormTermType",
    "get_rxnorm_service",
    "reset_rxnorm_service",
    # SNOMED CT Service
    "ConceptMatch",
    "CrossMapResult",
    "HierarchyResult",
    "MatchConfidence",
    "SemanticType",
    "SNOMEDConcept",
    "SNOMEDService",
    "get_snomed_service",
    "reset_snomed_service",
    # LLM Service
    "CostEstimate",
    "LLMConfig",
    "LLMMessage",
    "LLMModel",
    "LLMProvider",
    "LLMResponse",
    "LLMService",
    "TokenUsage",
    "estimate_cost",
    "estimate_tokens",
    "get_llm_service",
    "reset_llm_service",
    # LLM Summarizer
    "AssessmentPlanItem",
    "AssessmentPlanResult",
    "ClinicalSection",
    "ClinicalSummarizerLLM",
    "ClinicalSummaryResult",
    "DischargeSummaryResult",
    "EncounterData",
    "KeyFinding",
    "KeyFindingsResult",
    "SummaryLength",
    "get_clinical_summarizer_llm",
    "reset_clinical_summarizer_llm",
    # Calculator Builder Service
    "CalculatorBuilderService",
    "CalculatorExecutionResult",
    "CalculatorInputDefinition",
    "FormulaValidationResult",
    "get_calculator_builder_service",
    "reset_calculator_builder_service",
    # SMART on FHIR Service
    "SMARTAuthorizationError",
    "FHIRRequestError",
    "LaunchContext",
    "OAuthState",
    "SMARTClient",
    "SMARTClientError",
    "TokenError",
    "TokenSet",
    "TokenType",
    "get_smart_client",
    "reset_smart_client",
    # Medication Reconciliation Service
    "DiscrepancyAlert",
    "DiscrepancySeverity",
    "DiscrepancyType",
    "MedicationEntry",
    "MedicationListAnalysis",
    "MedicationMatch",
    "MedicationReconciliationService",
    "MedicationRoute",
    "ReconciliationResult",
    "ReconciliationStatus",
    "TherapeuticDuplicate",
    "get_medication_reconciliation_service",
    "reset_medication_reconciliation_service",
    # Clinical Note Generator Service
    "ClinicalNoteGeneratorService",
    "NoteConfidenceLevel",
    "NoteEncounterData",
    "GeneratedNote",
    "NoteEnhancementResult",
    "NoteGenerationRequest",
    "NoteSection",
    "NoteSectionTemplate",
    "NoteStatus",
    "NoteTemplate",
    "NoteType",
    "NoteValidationResult",
    "PatientData",
    "SectionStatus",
    "get_note_generator_service",
    "reset_note_generator_service",
    # Quality Measure Service
    "AgeRange",
    "AgeUnit",
    "ComplianceStatus",
    "EligibilityCriteria",
    "MeasureCategory",
    "MeasurePerformance",
    "MeasurePriority",
    "MeasureResult",
    "MeasureType",
    "NumeratorCriteria",
    "PatientEvaluationResult",
    "PatientGap",
    "PerformanceReport",
    "QualityMeasure",
    "QualityMeasureService",
    "get_quality_measure_service",
    "reset_quality_measure_service",
    # Patient Timeline Service
    "CareGap",
    "EventSeverity",
    "GapAnalysisResult",
    "GapPriority",
    "GapType",
    "PatientTimeline",
    "PatientTimelineService",
    "TimelineEvent",
    "TimelineEventType",
    "TimelineFilter",
    "TimelineSummary",
    "get_patient_timeline_service",
    "reset_patient_timeline_service",
    # Data Quality Dashboard Service
    "DataQualityService",
    "DQDCategory",
    "DQDCategorySummary",
    "DQDCheckDefinition",
    "DQDCheckResult",
    "DQDHistoryEntry",
    "DQDIssue",
    "DQDRunResult",
    "DQDSeverity",
    "DQDStatus",
    "DQDSubcategory",
    "DQDSummary",
    "DQDTableSummary",
    "OMOPTable",
    "get_data_quality_service",
    "reset_data_quality_service",
    # Value Set Service
    "FilterOperator",
    "InclusionRule",
    "InclusionRuleType",
    "ValidationResult",
    "ValueSet",
    "ValueSetCode",
    "ValueSetExpansionResult",
    "ValueSetService",
    "ValueSetStatus",
    "ValueSetType",
    "ValueSetVersion",
    "get_value_set_service",
    "reset_value_set_service",
    # CDS Hooks Service
    "CDSHooksService",
    "CDSCard",
    "CDSResponse",
    "CDSIndicator",
    "CDSServiceDefinition",
    "HookType",
    "get_cds_hooks_service",
    "reset_cds_hooks_service",
    # Bulk Export Service
    "BulkExportService",
    "ExportJob",
    "ExportStatus",
    "ExportType",
    "ResourceType",
    "get_bulk_export_service",
    "reset_bulk_export_service",
    # Synthetic Data Service
    "AgeDistribution",
    "ConditionPrevalence",
    "FHIRBundle",
    "GenderDistribution",
    "GenerationJob",
    "GenerationTemplate",
    "SyntheticJobStatus",
    "LabCorrelation",
    "MedicationPattern",
    "OutputFormat",
    "PrivacyConfig",
    "PrivacyReport",
    "RaceDistribution",
    "SynthesisConfig",
    "SyntheticDataService",
    "SyntheticPatient",
    "ValidationReport",
    "get_synthetic_data_service",
    "reset_synthetic_data_service",
    # TEFCA Service
    "TEFCAAuditEventType",
    "TEFCAAuditLog",
    "TEFCAClinicalDocument",
    "TEFCAConsentStatus",
    "DirectMessage",
    "DirectMessageStatus",
    "DocumentClass",
    "DocumentQueryResponse",
    "TEFCADocumentReference",
    "ExchangePurpose",
    "TEFCAMatchConfidence",
    "PatientConsent",
    "PatientDemographics",
    "PatientMatch",
    "QHIN",
    "QHINStatus",
    "QueryResponse",
    "SendResult",
    "TEFCAQuery",
    "TEFCAService",
    "TEFCAValidationResult",
    "get_tefca_service",
    "reset_tefca_service",
]
