export interface DemoClinicalFact {
  id: string;
  patient_id: string;
  fact_type: string;
  concept_name: string;
  concept_id: string;
  vocabulary_id: string;
  value?: string;
  unit?: string;
  assertion: string;
  source_document_id: string;
  confidence: number;
}

export const DEMO_CLINICAL_FACTS: Record<string, DemoClinicalFact[]> = {
  "pat-001": [
    {
      id: "fact-001",
      patient_id: "pat-001",
      fact_type: "condition",
      concept_name: "Type 2 Diabetes Mellitus",
      concept_id: "4193704",
      vocabulary_id: "SNOMED",
      assertion: "present",
      source_document_id: "doc-001",
      confidence: 0.97,
    },
    {
      id: "fact-002",
      patient_id: "pat-001",
      fact_type: "condition",
      concept_name: "Essential Hypertension",
      concept_id: "320128",
      vocabulary_id: "SNOMED",
      assertion: "present",
      source_document_id: "doc-001",
      confidence: 0.96,
    },
    {
      id: "fact-003",
      patient_id: "pat-001",
      fact_type: "medication",
      concept_name: "Metformin 1000mg BID",
      concept_id: "1503297",
      vocabulary_id: "RxNorm",
      value: "1000",
      unit: "mg",
      assertion: "present",
      source_document_id: "doc-001",
      confidence: 0.98,
    },
    {
      id: "fact-004",
      patient_id: "pat-001",
      fact_type: "medication",
      concept_name: "Lisinopril 20mg Daily",
      concept_id: "1308216",
      vocabulary_id: "RxNorm",
      value: "20",
      unit: "mg",
      assertion: "present",
      source_document_id: "doc-001",
      confidence: 0.97,
    },
    {
      id: "fact-005",
      patient_id: "pat-001",
      fact_type: "medication",
      concept_name: "Insulin Glargine",
      concept_id: "1596977",
      vocabulary_id: "RxNorm",
      value: "18",
      unit: "units",
      assertion: "present",
      source_document_id: "doc-001",
      confidence: 0.96,
    },
    {
      id: "fact-006",
      patient_id: "pat-001",
      fact_type: "lab_result",
      concept_name: "Hemoglobin A1c",
      concept_id: "3004410",
      vocabulary_id: "LOINC",
      value: "8.2",
      unit: "%",
      assertion: "present",
      source_document_id: "doc-001",
      confidence: 0.99,
    },
    {
      id: "fact-007",
      patient_id: "pat-001",
      fact_type: "lab_result",
      concept_name: "Serum Creatinine",
      concept_id: "3016723",
      vocabulary_id: "LOINC",
      value: "1.1",
      unit: "mg/dL",
      assertion: "present",
      source_document_id: "doc-001",
      confidence: 0.98,
    },
    {
      id: "fact-008",
      patient_id: "pat-001",
      fact_type: "lab_result",
      concept_name: "Potassium",
      concept_id: "3023103",
      vocabulary_id: "LOINC",
      value: "4.2",
      unit: "mEq/L",
      assertion: "present",
      source_document_id: "doc-003",
      confidence: 0.97,
    },
    {
      id: "fact-009",
      patient_id: "pat-001",
      fact_type: "lab_result",
      concept_name: "Glomerular Filtration Rate",
      concept_id: "3030354",
      vocabulary_id: "LOINC",
      value: "68",
      unit: "mL/min",
      assertion: "present",
      source_document_id: "doc-003",
      confidence: 0.96,
    },
    {
      id: "fact-010",
      patient_id: "pat-001",
      fact_type: "lab_result",
      concept_name: "Blood Urea Nitrogen",
      concept_id: "3013682",
      vocabulary_id: "LOINC",
      value: "22",
      unit: "mg/dL",
      assertion: "present",
      source_document_id: "doc-003",
      confidence: 0.95,
    },
    {
      id: "fact-011",
      patient_id: "pat-001",
      fact_type: "vital_sign",
      concept_name: "Blood Pressure",
      concept_id: "3004249",
      vocabulary_id: "LOINC",
      value: "142/88",
      unit: "mmHg",
      assertion: "present",
      source_document_id: "doc-001",
      confidence: 0.94,
    },
    {
      id: "fact-012",
      patient_id: "pat-001",
      fact_type: "measurement",
      concept_name: "BMI",
      concept_id: "3038553",
      vocabulary_id: "LOINC",
      value: "31.2",
      unit: "kg/m2",
      assertion: "present",
      source_document_id: "doc-003",
      confidence: 0.97,
    },
    {
      id: "fact-013",
      patient_id: "pat-001",
      fact_type: "condition",
      concept_name: "Peripheral Neuropathy",
      concept_id: "4271564",
      vocabulary_id: "SNOMED",
      assertion: "present",
      source_document_id: "doc-003",
      confidence: 0.91,
    },
    {
      id: "fact-014",
      patient_id: "pat-001",
      fact_type: "vital_sign",
      concept_name: "Blood Pressure (Follow-up)",
      concept_id: "3004249",
      vocabulary_id: "LOINC",
      value: "128/78",
      unit: "mmHg",
      assertion: "present",
      source_document_id: "doc-002",
      confidence: 0.95,
    },
  ],
  "pat-002": [
    {
      id: "fact-015",
      patient_id: "pat-002",
      fact_type: "condition",
      concept_name: "Major Depressive Disorder",
      concept_id: "4152280",
      vocabulary_id: "SNOMED",
      assertion: "present",
      source_document_id: "doc-004",
      confidence: 0.98,
    },
    {
      id: "fact-016",
      patient_id: "pat-002",
      fact_type: "medication",
      concept_name: "Sertraline 100mg",
      concept_id: "1000048",
      vocabulary_id: "RxNorm",
      value: "100",
      unit: "mg",
      assertion: "present",
      source_document_id: "doc-004",
      confidence: 0.97,
    },
    {
      id: "fact-017",
      patient_id: "pat-002",
      fact_type: "assessment",
      concept_name: "PHQ-9 Depression Score",
      concept_id: "40758891",
      vocabulary_id: "LOINC",
      value: "14",
      assertion: "present",
      source_document_id: "doc-004",
      confidence: 0.96,
    },
    {
      id: "fact-018",
      patient_id: "pat-002",
      fact_type: "symptom",
      concept_name: "Insomnia",
      concept_id: "4196636",
      vocabulary_id: "SNOMED",
      assertion: "present",
      source_document_id: "doc-004",
      confidence: 0.95,
    },
    {
      id: "fact-019",
      patient_id: "pat-002",
      fact_type: "symptom",
      concept_name: "Fatigue",
      concept_id: "4223659",
      vocabulary_id: "SNOMED",
      assertion: "present",
      source_document_id: "doc-005",
      confidence: 0.93,
    },
    {
      id: "fact-020",
      patient_id: "pat-002",
      fact_type: "assessment",
      concept_name: "GAD-7 Anxiety Score",
      concept_id: "40758893",
      vocabulary_id: "LOINC",
      value: "8",
      assertion: "present",
      source_document_id: "doc-005",
      confidence: 0.97,
    },
    {
      id: "fact-021",
      patient_id: "pat-002",
      fact_type: "condition",
      concept_name: "Generalized Anxiety Disorder",
      concept_id: "441542",
      vocabulary_id: "SNOMED",
      assertion: "present",
      source_document_id: "doc-005",
      confidence: 0.90,
    },
    {
      id: "fact-022",
      patient_id: "pat-002",
      fact_type: "symptom",
      concept_name: "Anhedonia",
      concept_id: "4284194",
      vocabulary_id: "SNOMED",
      assertion: "present",
      source_document_id: "doc-004",
      confidence: 0.94,
    },
  ],
  "pat-003": [
    {
      id: "fact-023",
      patient_id: "pat-003",
      fact_type: "condition",
      concept_name: "Heart Failure",
      concept_id: "316139",
      vocabulary_id: "SNOMED",
      assertion: "present",
      source_document_id: "doc-006",
      confidence: 0.97,
    },
    {
      id: "fact-024",
      patient_id: "pat-003",
      fact_type: "condition",
      concept_name: "Atrial Fibrillation",
      concept_id: "313217",
      vocabulary_id: "SNOMED",
      assertion: "present",
      source_document_id: "doc-006",
      confidence: 0.99,
    },
    {
      id: "fact-025",
      patient_id: "pat-003",
      fact_type: "medication",
      concept_name: "Furosemide 40mg",
      concept_id: "1395058",
      vocabulary_id: "RxNorm",
      value: "40",
      unit: "mg",
      assertion: "present",
      source_document_id: "doc-006",
      confidence: 0.97,
    },
    {
      id: "fact-026",
      patient_id: "pat-003",
      fact_type: "medication",
      concept_name: "Warfarin 5mg",
      concept_id: "1310149",
      vocabulary_id: "RxNorm",
      value: "5",
      unit: "mg",
      assertion: "present",
      source_document_id: "doc-006",
      confidence: 0.98,
    },
    {
      id: "fact-027",
      patient_id: "pat-003",
      fact_type: "medication",
      concept_name: "Metoprolol 50mg",
      concept_id: "1307046",
      vocabulary_id: "RxNorm",
      value: "50",
      unit: "mg",
      assertion: "present",
      source_document_id: "doc-006",
      confidence: 0.97,
    },
    {
      id: "fact-028",
      patient_id: "pat-003",
      fact_type: "measurement",
      concept_name: "Ejection Fraction",
      concept_id: "3037121",
      vocabulary_id: "LOINC",
      value: "35",
      unit: "%",
      assertion: "present",
      source_document_id: "doc-007",
      confidence: 0.97,
    },
    {
      id: "fact-029",
      patient_id: "pat-003",
      fact_type: "lab_result",
      concept_name: "BNP",
      concept_id: "3022217",
      vocabulary_id: "LOINC",
      value: "1847",
      unit: "pg/mL",
      assertion: "present",
      source_document_id: "doc-006",
      confidence: 0.98,
    },
    {
      id: "fact-030",
      patient_id: "pat-003",
      fact_type: "lab_result",
      concept_name: "INR",
      concept_id: "3010813",
      vocabulary_id: "LOINC",
      value: "2.3",
      assertion: "present",
      source_document_id: "doc-006",
      confidence: 0.98,
    },
    {
      id: "fact-031",
      patient_id: "pat-003",
      fact_type: "lab_result",
      concept_name: "Serum Creatinine",
      concept_id: "3016723",
      vocabulary_id: "LOINC",
      value: "1.4",
      unit: "mg/dL",
      assertion: "present",
      source_document_id: "doc-006",
      confidence: 0.96,
    },
    {
      id: "fact-032",
      patient_id: "pat-003",
      fact_type: "condition",
      concept_name: "Peripheral Edema",
      concept_id: "4129519",
      vocabulary_id: "SNOMED",
      assertion: "present",
      source_document_id: "doc-006",
      confidence: 0.93,
    },
    {
      id: "fact-033",
      patient_id: "pat-003",
      fact_type: "condition",
      concept_name: "Mitral Regurgitation",
      concept_id: "314378",
      vocabulary_id: "SNOMED",
      assertion: "present",
      source_document_id: "doc-007",
      confidence: 0.95,
    },
    {
      id: "fact-034",
      patient_id: "pat-003",
      fact_type: "measurement",
      concept_name: "BNP (Discharge)",
      concept_id: "3022217",
      vocabulary_id: "LOINC",
      value: "620",
      unit: "pg/mL",
      assertion: "present",
      source_document_id: "doc-006",
      confidence: 0.97,
    },
  ],
  "pat-004": [
    {
      id: "fact-035",
      patient_id: "pat-004",
      fact_type: "condition",
      concept_name: "Chronic Kidney Disease Stage 4",
      concept_id: "443611",
      vocabulary_id: "SNOMED",
      assertion: "present",
      source_document_id: "doc-008",
      confidence: 0.98,
    },
    {
      id: "fact-036",
      patient_id: "pat-004",
      fact_type: "condition",
      concept_name: "Anemia of Chronic Disease",
      concept_id: "4144746",
      vocabulary_id: "SNOMED",
      assertion: "present",
      source_document_id: "doc-008",
      confidence: 0.95,
    },
    {
      id: "fact-037",
      patient_id: "pat-004",
      fact_type: "medication",
      concept_name: "Epoetin Alfa",
      concept_id: "1304919",
      vocabulary_id: "RxNorm",
      assertion: "present",
      source_document_id: "doc-008",
      confidence: 0.95,
    },
    {
      id: "fact-038",
      patient_id: "pat-004",
      fact_type: "medication",
      concept_name: "Sodium Bicarbonate",
      concept_id: "1305058",
      vocabulary_id: "RxNorm",
      assertion: "present",
      source_document_id: "doc-008",
      confidence: 0.94,
    },
    {
      id: "fact-039",
      patient_id: "pat-004",
      fact_type: "medication",
      concept_name: "Calcitriol",
      concept_id: "1305455",
      vocabulary_id: "RxNorm",
      assertion: "present",
      source_document_id: "doc-008",
      confidence: 0.93,
    },
    {
      id: "fact-040",
      patient_id: "pat-004",
      fact_type: "lab_result",
      concept_name: "Glomerular Filtration Rate",
      concept_id: "3030354",
      vocabulary_id: "LOINC",
      value: "22",
      unit: "mL/min",
      assertion: "present",
      source_document_id: "doc-008",
      confidence: 0.97,
    },
    {
      id: "fact-041",
      patient_id: "pat-004",
      fact_type: "lab_result",
      concept_name: "Hemoglobin",
      concept_id: "3000963",
      vocabulary_id: "LOINC",
      value: "9.8",
      unit: "g/dL",
      assertion: "present",
      source_document_id: "doc-008",
      confidence: 0.98,
    },
    {
      id: "fact-042",
      patient_id: "pat-004",
      fact_type: "lab_result",
      concept_name: "Potassium",
      concept_id: "3023103",
      vocabulary_id: "LOINC",
      value: "5.1",
      unit: "mEq/L",
      assertion: "present",
      source_document_id: "doc-008",
      confidence: 0.96,
    },
    {
      id: "fact-043",
      patient_id: "pat-004",
      fact_type: "lab_result",
      concept_name: "Phosphorus",
      concept_id: "3015736",
      vocabulary_id: "LOINC",
      value: "5.8",
      unit: "mg/dL",
      assertion: "present",
      source_document_id: "doc-008",
      confidence: 0.97,
    },
    {
      id: "fact-044",
      patient_id: "pat-004",
      fact_type: "lab_result",
      concept_name: "Parathyroid Hormone",
      concept_id: "3034962",
      vocabulary_id: "LOINC",
      value: "189",
      unit: "pg/mL",
      assertion: "present",
      source_document_id: "doc-009",
      confidence: 0.95,
    },
  ],
  "pat-005": [
    {
      id: "fact-045",
      patient_id: "pat-005",
      fact_type: "condition",
      concept_name: "Persistent Asthma, Moderate",
      concept_id: "4145356",
      vocabulary_id: "SNOMED",
      assertion: "present",
      source_document_id: "doc-010",
      confidence: 0.97,
    },
    {
      id: "fact-046",
      patient_id: "pat-005",
      fact_type: "medication",
      concept_name: "Albuterol HFA",
      concept_id: "1154343",
      vocabulary_id: "RxNorm",
      assertion: "present",
      source_document_id: "doc-010",
      confidence: 0.98,
    },
    {
      id: "fact-047",
      patient_id: "pat-005",
      fact_type: "medication",
      concept_name: "Fluticasone/Salmeterol",
      concept_id: "1149196",
      vocabulary_id: "RxNorm",
      assertion: "present",
      source_document_id: "doc-010",
      confidence: 0.97,
    },
    {
      id: "fact-048",
      patient_id: "pat-005",
      fact_type: "measurement",
      concept_name: "FEV1",
      concept_id: "3024653",
      vocabulary_id: "LOINC",
      value: "78",
      unit: "%",
      assertion: "present",
      source_document_id: "doc-010",
      confidence: 0.95,
    },
    {
      id: "fact-049",
      patient_id: "pat-005",
      fact_type: "measurement",
      concept_name: "Peak Expiratory Flow",
      concept_id: "3024171",
      vocabulary_id: "LOINC",
      value: "380",
      unit: "L/min",
      assertion: "present",
      source_document_id: "doc-010",
      confidence: 0.96,
    },
    {
      id: "fact-050",
      patient_id: "pat-005",
      fact_type: "lab_result",
      concept_name: "Eosinophils",
      concept_id: "3013115",
      vocabulary_id: "LOINC",
      value: "450",
      unit: "cells/uL",
      assertion: "present",
      source_document_id: "doc-010",
      confidence: 0.94,
    },
  ],
};
