import type { Document } from "@/lib/api";

export const DEMO_DOCUMENTS: Document[] = [
  {
    id: "doc-001",
    patient_id: "pat-001",
    note_type: "Discharge Summary",
    text: "Patient John Smith is a 62-year-old male admitted for hyperglycemic crisis. History significant for poorly controlled Type 2 Diabetes Mellitus on metformin 1000mg BID and essential hypertension on lisinopril 20mg daily. A1c found to be 8.2% on admission. Renal function stable with creatinine 1.1 mg/dL. Discharged with insulin glargine added to regimen and endocrinology follow-up in 2 weeks.",
    metadata: { department: "Internal Medicine", provider: "Dr. Adams" },
    status: "completed",
    job_id: "job-001",
    created_at: "2026-01-15T09:00:00Z",
    processed_at: "2026-01-15T09:02:30Z",
  },
  {
    id: "doc-002",
    patient_id: "pat-001",
    note_type: "Progress Note",
    text: "Follow-up visit for Mr. Smith, 2 weeks post-discharge. Reports improved glucose control with fasting BG 110-140 mg/dL range on new insulin glargine regimen. Blood pressure well controlled at 128/78 mmHg on lisinopril 20mg. No hypoglycemic episodes reported. Continue current medications with repeat A1c in 3 months.",
    metadata: { department: "Internal Medicine", provider: "Dr. Adams" },
    status: "completed",
    job_id: "job-002",
    created_at: "2026-01-29T10:30:00Z",
    processed_at: "2026-01-29T10:32:15Z",
  },
  {
    id: "doc-003",
    patient_id: "pat-001",
    note_type: "H&P",
    text: "62-year-old male presenting for annual physical. PMH: Type 2 DM diagnosed 2018, essential HTN diagnosed 2015. Current medications include metformin 1000mg BID, insulin glargine 18 units nightly, lisinopril 20mg daily. Exam notable for BMI 31.2, mild peripheral neuropathy bilateral feet. Labs ordered including CMP, CBC, lipid panel, A1c, urine microalbumin.",
    metadata: { department: "Primary Care", provider: "Dr. Patel" },
    status: "completed",
    job_id: "job-003",
    created_at: "2026-02-10T08:15:00Z",
    processed_at: "2026-02-10T08:17:45Z",
  },
  {
    id: "doc-004",
    patient_id: "pat-002",
    note_type: "Progress Note",
    text: "Maria Garcia is a 40-year-old female seen for medication management of Major Depressive Disorder. Patient reports partial improvement on sertraline 100mg daily, with PHQ-9 score decreased from 18 to 12. Continued insomnia and anhedonia present. Plan to increase sertraline to 150mg daily and add sleep hygiene counseling. Follow-up in 4 weeks.",
    metadata: { department: "Psychiatry", provider: "Dr. Nguyen" },
    status: "completed",
    job_id: "job-004",
    created_at: "2026-01-18T11:00:00Z",
    processed_at: "2026-01-18T11:03:10Z",
  },
  {
    id: "doc-005",
    patient_id: "pat-002",
    note_type: "Consult Note",
    text: "Psychiatry consultation requested for medication optimization. Patient has a 3-year history of recurrent MDD, currently on second adequate trial. GAD-7 score 14 indicates comorbid moderate anxiety. Recommend augmentation with bupropion XL 150mg daily given fatigue and weight gain concerns. Consider CBT referral for adjunctive psychotherapy.",
    metadata: { department: "Psychiatry", provider: "Dr. Kim" },
    status: "completed",
    job_id: "job-005",
    created_at: "2026-02-05T14:00:00Z",
    processed_at: "2026-02-05T14:02:50Z",
  },
  {
    id: "doc-006",
    patient_id: "pat-003",
    note_type: "Discharge Summary",
    text: "Mrs. Johnson is a 75-year-old female admitted with acute decompensated heart failure, NYHA Class III. BNP elevated at 1850 pg/mL on admission, down to 620 at discharge. Treated with IV furosemide with 4kg net diuresis over 3-day admission. Atrial fibrillation rate controlled with metoprolol, INR therapeutic at 2.4 on warfarin. Discharged on optimized oral diuretic regimen with cardiology follow-up in 1 week.",
    metadata: { department: "Cardiology", provider: "Dr. Thompson" },
    status: "completed",
    job_id: "job-006",
    created_at: "2026-01-20T15:00:00Z",
    processed_at: "2026-01-20T15:03:20Z",
  },
  {
    id: "doc-007",
    patient_id: "pat-003",
    note_type: "Consult Note",
    text: "Cardiology consultation for heart failure management optimization. Echocardiogram shows EF 30%, moderate mitral regurgitation, dilated left atrium. Patient on guideline-directed medical therapy with furosemide, metoprolol, and warfarin for atrial fibrillation. Recommend adding sacubitril/valsartan and considering ICD evaluation given reduced ejection fraction. Cardiac rehabilitation referral placed.",
    metadata: { department: "Cardiology", provider: "Dr. Reynolds" },
    status: "completed",
    job_id: "job-007",
    created_at: "2026-02-03T09:30:00Z",
    processed_at: "2026-02-03T09:33:00Z",
  },
  {
    id: "doc-008",
    patient_id: "pat-004",
    note_type: "Progress Note",
    text: "Robert Williams is a 68-year-old male with CKD Stage 4, GFR 22 mL/min, seen for routine nephrology follow-up. Hemoglobin 9.8 g/dL on current erythropoietin dose. Bicarbonate level 18 mEq/L, continuing sodium bicarbonate supplementation. Phosphorus mildly elevated at 5.2 mg/dL. AV fistula creation discussed for potential hemodialysis planning within next 6-12 months.",
    metadata: { department: "Nephrology", provider: "Dr. Ramirez" },
    status: "completed",
    job_id: "job-008",
    created_at: "2026-01-25T09:30:00Z",
    processed_at: "2026-01-25T09:32:40Z",
  },
  {
    id: "doc-009",
    patient_id: "pat-004",
    note_type: "Consult Note",
    text: "Nephrology consultation for advanced CKD management. Patient has progressive Stage 4 CKD attributed to longstanding hypertension and type 2 diabetes. Current GFR trend shows decline from 28 to 22 over past 8 months. Anemia managed with epoetin alfa, target Hgb 10-11 g/dL. Initiated discussion regarding transplant evaluation and dialysis modality education. Dietary phosphorus restriction reinforced.",
    metadata: { department: "Nephrology", provider: "Dr. Ramirez" },
    status: "failed",
    job_id: "job-009",
    created_at: "2026-02-12T13:00:00Z",
    processed_at: null,
  },
  {
    id: "doc-010",
    patient_id: "pat-005",
    note_type: "H&P",
    text: "Sarah Chen is a 33-year-old female presenting to the ED with acute asthma exacerbation. Reports 3 days of progressive dyspnea, wheeze, and cough following URI symptoms. Uses albuterol HFA rescue inhaler and fluticasone/salmeterol maintenance. Peak flow 55% of personal best on arrival. Administered nebulized albuterol and ipratropium with IV methylprednisolone 125mg. Observation admission for serial assessments.",
    metadata: { department: "Emergency Medicine", provider: "Dr. Liu" },
    status: "processing",
    job_id: "job-010",
    created_at: "2026-02-18T16:45:00Z",
    processed_at: null,
  },
];
