export interface DemoMention {
  id: string;
  document_id: string;
  text: string;
  start_offset: number;
  end_offset: number;
  mention_type: string;
  assertion: string;
  temporality: string;
  experiencer: string;
  candidates: Array<{
    concept_id: string;
    concept_name: string;
    vocabulary_id: string;
    confidence: number;
  }>;
}

export const DEMO_MENTIONS: Record<string, DemoMention[]> = {
  "doc-001": [
    {
      id: "men-001",
      document_id: "doc-001",
      text: "Type 2 Diabetes Mellitus",
      start_offset: 105,
      end_offset: 129,
      mention_type: "condition",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "4193704", concept_name: "Type 2 diabetes mellitus", vocabulary_id: "SNOMED", confidence: 0.97 },
        { concept_id: "201826", concept_name: "Type 2 diabetes mellitus", vocabulary_id: "OMOP", confidence: 0.95 },
      ],
    },
    {
      id: "men-002",
      document_id: "doc-001",
      text: "metformin 1000mg",
      start_offset: 133,
      end_offset: 149,
      mention_type: "medication",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "1503297", concept_name: "Metformin", vocabulary_id: "RxNorm", confidence: 0.98 },
      ],
    },
    {
      id: "men-003",
      document_id: "doc-001",
      text: "essential hypertension",
      start_offset: 158,
      end_offset: 180,
      mention_type: "condition",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "320128", concept_name: "Essential hypertension", vocabulary_id: "SNOMED", confidence: 0.96 },
      ],
    },
    {
      id: "men-004",
      document_id: "doc-001",
      text: "lisinopril 20mg",
      start_offset: 184,
      end_offset: 199,
      mention_type: "medication",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "1308216", concept_name: "Lisinopril", vocabulary_id: "RxNorm", confidence: 0.97 },
      ],
    },
    {
      id: "men-005",
      document_id: "doc-001",
      text: "A1c found to be 8.2%",
      start_offset: 215,
      end_offset: 235,
      mention_type: "lab_result",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "3004410", concept_name: "Hemoglobin A1c", vocabulary_id: "LOINC", confidence: 0.99 },
      ],
    },
    {
      id: "men-006",
      document_id: "doc-001",
      text: "creatinine 1.1 mg/dL",
      start_offset: 271,
      end_offset: 291,
      mention_type: "lab_result",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "3016723", concept_name: "Serum creatinine", vocabulary_id: "LOINC", confidence: 0.98 },
      ],
    },
  ],
  "doc-002": [
    {
      id: "men-007",
      document_id: "doc-002",
      text: "insulin glargine",
      start_offset: 95,
      end_offset: 111,
      mention_type: "medication",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "1596977", concept_name: "Insulin glargine", vocabulary_id: "RxNorm", confidence: 0.97 },
      ],
    },
    {
      id: "men-008",
      document_id: "doc-002",
      text: "Blood pressure well controlled at 128/78 mmHg",
      start_offset: 162,
      end_offset: 208,
      mention_type: "vital_sign",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "3004249", concept_name: "Systolic blood pressure", vocabulary_id: "LOINC", confidence: 0.95 },
      ],
    },
    {
      id: "men-009",
      document_id: "doc-002",
      text: "lisinopril 20mg",
      start_offset: 212,
      end_offset: 227,
      mention_type: "medication",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "1308216", concept_name: "Lisinopril", vocabulary_id: "RxNorm", confidence: 0.97 },
      ],
    },
  ],
  "doc-003": [
    {
      id: "men-010",
      document_id: "doc-003",
      text: "Type 2 DM",
      start_offset: 53,
      end_offset: 63,
      mention_type: "condition",
      assertion: "present",
      temporality: "historical",
      experiencer: "patient",
      candidates: [
        { concept_id: "4193704", concept_name: "Type 2 diabetes mellitus", vocabulary_id: "SNOMED", confidence: 0.94 },
      ],
    },
    {
      id: "men-011",
      document_id: "doc-003",
      text: "essential HTN",
      start_offset: 79,
      end_offset: 92,
      mention_type: "condition",
      assertion: "present",
      temporality: "historical",
      experiencer: "patient",
      candidates: [
        { concept_id: "320128", concept_name: "Essential hypertension", vocabulary_id: "SNOMED", confidence: 0.93 },
      ],
    },
    {
      id: "men-012",
      document_id: "doc-003",
      text: "peripheral neuropathy bilateral feet",
      start_offset: 248,
      end_offset: 284,
      mention_type: "condition",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "4271564", concept_name: "Peripheral neuropathy", vocabulary_id: "SNOMED", confidence: 0.91 },
      ],
    },
    {
      id: "men-013",
      document_id: "doc-003",
      text: "metformin 1000mg BID",
      start_offset: 136,
      end_offset: 156,
      mention_type: "medication",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "1503297", concept_name: "Metformin", vocabulary_id: "RxNorm", confidence: 0.98 },
      ],
    },
  ],
  "doc-004": [
    {
      id: "men-014",
      document_id: "doc-004",
      text: "Major Depressive Disorder",
      start_offset: 72,
      end_offset: 97,
      mention_type: "condition",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "4152280", concept_name: "Major depressive disorder", vocabulary_id: "SNOMED", confidence: 0.98 },
      ],
    },
    {
      id: "men-015",
      document_id: "doc-004",
      text: "sertraline 100mg",
      start_offset: 131,
      end_offset: 147,
      mention_type: "medication",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "1000048", concept_name: "Sertraline", vocabulary_id: "RxNorm", confidence: 0.97 },
      ],
    },
    {
      id: "men-016",
      document_id: "doc-004",
      text: "PHQ-9 score decreased from 18 to 12",
      start_offset: 160,
      end_offset: 195,
      mention_type: "assessment",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "40758891", concept_name: "PHQ-9 Depression Scale", vocabulary_id: "LOINC", confidence: 0.96 },
      ],
    },
    {
      id: "men-017",
      document_id: "doc-004",
      text: "insomnia",
      start_offset: 208,
      end_offset: 216,
      mention_type: "symptom",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "4196636", concept_name: "Insomnia", vocabulary_id: "SNOMED", confidence: 0.95 },
      ],
    },
    {
      id: "men-018",
      document_id: "doc-004",
      text: "anhedonia",
      start_offset: 221,
      end_offset: 230,
      mention_type: "symptom",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "4284194", concept_name: "Anhedonia", vocabulary_id: "SNOMED", confidence: 0.94 },
      ],
    },
  ],
  "doc-005": [
    {
      id: "men-019",
      document_id: "doc-005",
      text: "recurrent MDD",
      start_offset: 78,
      end_offset: 92,
      mention_type: "condition",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "4152280", concept_name: "Major depressive disorder", vocabulary_id: "SNOMED", confidence: 0.96 },
      ],
    },
    {
      id: "men-020",
      document_id: "doc-005",
      text: "GAD-7 score 14",
      start_offset: 137,
      end_offset: 151,
      mention_type: "assessment",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "40758893", concept_name: "GAD-7 Anxiety Scale", vocabulary_id: "LOINC", confidence: 0.97 },
      ],
    },
    {
      id: "men-021",
      document_id: "doc-005",
      text: "moderate anxiety",
      start_offset: 163,
      end_offset: 179,
      mention_type: "condition",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "441542", concept_name: "Generalized anxiety disorder", vocabulary_id: "SNOMED", confidence: 0.90 },
      ],
    },
    {
      id: "men-022",
      document_id: "doc-005",
      text: "bupropion XL 150mg",
      start_offset: 210,
      end_offset: 228,
      mention_type: "medication",
      assertion: "proposed",
      temporality: "future",
      experiencer: "patient",
      candidates: [
        { concept_id: "750982", concept_name: "Bupropion", vocabulary_id: "RxNorm", confidence: 0.98 },
      ],
    },
  ],
  "doc-006": [
    {
      id: "men-023",
      document_id: "doc-006",
      text: "acute decompensated heart failure",
      start_offset: 62,
      end_offset: 95,
      mention_type: "condition",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "316139", concept_name: "Heart failure", vocabulary_id: "SNOMED", confidence: 0.97 },
        { concept_id: "4229440", concept_name: "Acute heart failure", vocabulary_id: "SNOMED", confidence: 0.95 },
      ],
    },
    {
      id: "men-024",
      document_id: "doc-006",
      text: "BNP elevated at 1850 pg/mL",
      start_offset: 113,
      end_offset: 139,
      mention_type: "lab_result",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "3022217", concept_name: "BNP", vocabulary_id: "LOINC", confidence: 0.98 },
      ],
    },
    {
      id: "men-025",
      document_id: "doc-006",
      text: "Atrial fibrillation",
      start_offset: 215,
      end_offset: 234,
      mention_type: "condition",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "313217", concept_name: "Atrial fibrillation", vocabulary_id: "SNOMED", confidence: 0.99 },
      ],
    },
    {
      id: "men-026",
      document_id: "doc-006",
      text: "metoprolol",
      start_offset: 254,
      end_offset: 264,
      mention_type: "medication",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "1307046", concept_name: "Metoprolol", vocabulary_id: "RxNorm", confidence: 0.97 },
      ],
    },
    {
      id: "men-027",
      document_id: "doc-006",
      text: "INR therapeutic at 2.4",
      start_offset: 266,
      end_offset: 288,
      mention_type: "lab_result",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "3010813", concept_name: "INR", vocabulary_id: "LOINC", confidence: 0.98 },
      ],
    },
    {
      id: "men-028",
      document_id: "doc-006",
      text: "warfarin",
      start_offset: 292,
      end_offset: 300,
      mention_type: "medication",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "1310149", concept_name: "Warfarin", vocabulary_id: "RxNorm", confidence: 0.98 },
      ],
    },
  ],
  "doc-007": [
    {
      id: "men-029",
      document_id: "doc-007",
      text: "EF 30%",
      start_offset: 68,
      end_offset: 74,
      mention_type: "measurement",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "3037121", concept_name: "Ejection fraction", vocabulary_id: "LOINC", confidence: 0.97 },
      ],
    },
    {
      id: "men-030",
      document_id: "doc-007",
      text: "moderate mitral regurgitation",
      start_offset: 76,
      end_offset: 105,
      mention_type: "condition",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "314378", concept_name: "Mitral regurgitation", vocabulary_id: "SNOMED", confidence: 0.95 },
      ],
    },
    {
      id: "men-031",
      document_id: "doc-007",
      text: "sacubitril/valsartan",
      start_offset: 210,
      end_offset: 230,
      mention_type: "medication",
      assertion: "proposed",
      temporality: "future",
      experiencer: "patient",
      candidates: [
        { concept_id: "1656354", concept_name: "Sacubitril/valsartan", vocabulary_id: "RxNorm", confidence: 0.98 },
      ],
    },
  ],
  "doc-008": [
    {
      id: "men-032",
      document_id: "doc-008",
      text: "CKD Stage 4",
      start_offset: 48,
      end_offset: 60,
      mention_type: "condition",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "443611", concept_name: "Chronic kidney disease stage 4", vocabulary_id: "SNOMED", confidence: 0.98 },
      ],
    },
    {
      id: "men-033",
      document_id: "doc-008",
      text: "GFR 22 mL/min",
      start_offset: 62,
      end_offset: 76,
      mention_type: "lab_result",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "3030354", concept_name: "Glomerular filtration rate", vocabulary_id: "LOINC", confidence: 0.97 },
      ],
    },
    {
      id: "men-034",
      document_id: "doc-008",
      text: "Hemoglobin 9.8 g/dL",
      start_offset: 118,
      end_offset: 138,
      mention_type: "lab_result",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "3000963", concept_name: "Hemoglobin", vocabulary_id: "LOINC", confidence: 0.98 },
      ],
    },
    {
      id: "men-035",
      document_id: "doc-008",
      text: "erythropoietin",
      start_offset: 149,
      end_offset: 163,
      mention_type: "medication",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "1304919", concept_name: "Epoetin alfa", vocabulary_id: "RxNorm", confidence: 0.95 },
      ],
    },
    {
      id: "men-036",
      document_id: "doc-008",
      text: "Phosphorus mildly elevated at 5.2 mg/dL",
      start_offset: 218,
      end_offset: 258,
      mention_type: "lab_result",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "3015736", concept_name: "Phosphorus", vocabulary_id: "LOINC", confidence: 0.97 },
      ],
    },
  ],
  "doc-009": [
    {
      id: "men-037",
      document_id: "doc-009",
      text: "Stage 4 CKD",
      start_offset: 55,
      end_offset: 67,
      mention_type: "condition",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "443611", concept_name: "Chronic kidney disease stage 4", vocabulary_id: "SNOMED", confidence: 0.97 },
      ],
    },
    {
      id: "men-038",
      document_id: "doc-009",
      text: "GFR trend shows decline from 28 to 22",
      start_offset: 125,
      end_offset: 162,
      mention_type: "lab_result",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "3030354", concept_name: "Glomerular filtration rate", vocabulary_id: "LOINC", confidence: 0.96 },
      ],
    },
    {
      id: "men-039",
      document_id: "doc-009",
      text: "epoetin alfa",
      start_offset: 192,
      end_offset: 204,
      mention_type: "medication",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "1304919", concept_name: "Epoetin alfa", vocabulary_id: "RxNorm", confidence: 0.97 },
      ],
    },
  ],
  "doc-010": [
    {
      id: "men-040",
      document_id: "doc-010",
      text: "acute asthma exacerbation",
      start_offset: 56,
      end_offset: 81,
      mention_type: "condition",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "4145356", concept_name: "Acute exacerbation of asthma", vocabulary_id: "SNOMED", confidence: 0.97 },
      ],
    },
    {
      id: "men-041",
      document_id: "doc-010",
      text: "albuterol HFA",
      start_offset: 148,
      end_offset: 161,
      mention_type: "medication",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "1154343", concept_name: "Albuterol", vocabulary_id: "RxNorm", confidence: 0.98 },
      ],
    },
    {
      id: "men-042",
      document_id: "doc-010",
      text: "fluticasone/salmeterol",
      start_offset: 181,
      end_offset: 203,
      mention_type: "medication",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "1149196", concept_name: "Fluticasone/salmeterol", vocabulary_id: "RxNorm", confidence: 0.97 },
      ],
    },
    {
      id: "men-043",
      document_id: "doc-010",
      text: "Peak flow 55% of personal best",
      start_offset: 205,
      end_offset: 235,
      mention_type: "measurement",
      assertion: "present",
      temporality: "current",
      experiencer: "patient",
      candidates: [
        { concept_id: "3024171", concept_name: "Peak expiratory flow rate", vocabulary_id: "LOINC", confidence: 0.96 },
      ],
    },
  ],
};
