import type { Patient } from "@/lib/api";

export const DEMO_PATIENTS: Patient[] = [
  {
    id: "pat-001",
    external_id: "MRN-10001",
    name: "John Smith",
    gender: "male",
    birth_date: "1962-03-15",
    created_at: "2026-01-15T08:30:00Z",
    document_count: 3,
    fact_count: 14,
    node_count: 12,
    conditions: ["Type 2 Diabetes Mellitus", "Essential Hypertension"],
    medications: ["Metformin 1000mg", "Lisinopril 20mg"],
  },
  {
    id: "pat-002",
    external_id: "MRN-10002",
    name: "Maria Garcia",
    gender: "female",
    birth_date: "1985-07-22",
    created_at: "2026-01-18T10:15:00Z",
    document_count: 2,
    fact_count: 8,
    node_count: 6,
    conditions: ["Major Depressive Disorder"],
    medications: ["Sertraline 100mg"],
  },
  {
    id: "pat-003",
    external_id: "MRN-10003",
    name: "Mary Johnson",
    gender: "female",
    birth_date: "1950-11-08",
    created_at: "2026-01-20T14:45:00Z",
    document_count: 2,
    fact_count: 12,
    node_count: 10,
    conditions: ["Heart Failure", "Atrial Fibrillation"],
    medications: ["Furosemide 40mg", "Warfarin 5mg", "Metoprolol 50mg"],
  },
  {
    id: "pat-004",
    external_id: "MRN-10004",
    name: "Robert Williams",
    gender: "male",
    birth_date: "1958-01-30",
    created_at: "2026-01-25T09:00:00Z",
    document_count: 2,
    fact_count: 10,
    node_count: 8,
    conditions: ["Chronic Kidney Disease Stage 4", "Anemia of Chronic Disease"],
    medications: ["Epoetin Alfa", "Sodium Bicarbonate", "Calcitriol"],
  },
  {
    id: "pat-005",
    external_id: "MRN-10005",
    name: "Sarah Chen",
    gender: "female",
    birth_date: "1992-09-12",
    created_at: "2026-02-01T11:30:00Z",
    document_count: 1,
    fact_count: 6,
    node_count: 5,
    conditions: ["Persistent Asthma, Moderate"],
    medications: ["Albuterol HFA", "Fluticasone/Salmeterol"],
  },
];
