"""Pydantic schemas for Clinical Data Management & Data Cleaning (CLINICAL-2).

Covers data query management, validation rules, CDISC-compliant dataset
lifecycle, audit trails, and data cleaning metrics for clinical trials.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class QueryStatus(str, Enum):
    """Lifecycle status of a data query."""

    OPEN = "OPEN"
    ANSWERED = "ANSWERED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    REQUERIED = "REQUERIED"


class QueryCategory(str, Enum):
    """Category describing the nature of a data query."""

    MISSING_DATA = "MISSING_DATA"
    OUT_OF_RANGE = "OUT_OF_RANGE"
    INCONSISTENT = "INCONSISTENT"
    PROTOCOL_VIOLATION = "PROTOCOL_VIOLATION"
    CODING_ERROR = "CODING_ERROR"
    TRANSCRIPTION = "TRANSCRIPTION"
    DUPLICATE = "DUPLICATE"
    TIMELINESS = "TIMELINESS"


class DatasetStatus(str, Enum):
    """Lifecycle status of a clinical dataset."""

    DRAFT = "DRAFT"
    IN_REVIEW = "IN_REVIEW"
    CLEANED = "CLEANED"
    FROZEN = "FROZEN"
    LOCKED = "LOCKED"
    RELEASED = "RELEASED"
    ARCHIVED = "ARCHIVED"


class CDISCStandard(str, Enum):
    """CDISC data standard type."""

    SDTM = "SDTM"
    ADAM = "ADaM"
    DEFINE_XML = "Define-XML"
    SEND = "SEND"


class ValidationRuleType(str, Enum):
    """Type of validation rule applied to clinical data."""

    RANGE_CHECK = "RANGE_CHECK"
    CROSS_FIELD = "CROSS_FIELD"
    TEMPORAL = "TEMPORAL"
    COMPLETENESS = "COMPLETENESS"
    FORMAT = "FORMAT"
    REFERENTIAL_INTEGRITY = "REFERENTIAL_INTEGRITY"
    BUSINESS_RULE = "BUSINESS_RULE"


class DataLockLevel(str, Enum):
    """Lock level for a clinical dataset."""

    SOFT_LOCK = "SOFT_LOCK"
    HARD_LOCK = "HARD_LOCK"
    REGULATORY_LOCK = "REGULATORY_LOCK"


# ---------------------------------------------------------------------------
# Core models
# ---------------------------------------------------------------------------


class DataQuery(BaseModel):
    """A data query raised against a clinical trial data point."""

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(..., description="Unique query identifier")
    trial_id: str = Field(..., description="Owning trial identifier")
    site_id: str = Field(..., description="Site where the query was raised")
    patient_id: str = Field(..., description="Patient the query relates to")
    form_name: str = Field(..., description="CRF form name")
    field_name: str = Field(..., description="Field within the form")
    query_category: QueryCategory = Field(..., description="Nature of the query")
    description: str = Field(..., description="Detailed query description")
    current_value: Optional[str] = Field(None, description="Current data value")
    expected_value: Optional[str] = Field(None, description="Expected or valid value/range")
    status: QueryStatus = Field(default=QueryStatus.OPEN, description="Current query status")
    opened_by: str = Field(..., description="User who opened the query")
    opened_at: datetime = Field(..., description="Timestamp the query was opened")
    answered_by: Optional[str] = Field(None, description="User who answered the query")
    answered_at: Optional[datetime] = Field(None, description="Timestamp the query was answered")
    answer_text: Optional[str] = Field(None, description="Answer text from site")
    closed_by: Optional[str] = Field(None, description="User who closed the query")
    closed_at: Optional[datetime] = Field(None, description="Timestamp the query was closed")
    auto_generated: bool = Field(default=False, description="Whether query was auto-generated by a validation rule")
    requery_count: int = Field(default=0, description="Number of times this query was requeried")


class DataQueryCreate(BaseModel):
    """Request to create a new data query."""

    trial_id: str
    site_id: str
    patient_id: str
    form_name: str
    field_name: str
    query_category: QueryCategory
    description: str
    current_value: Optional[str] = None
    expected_value: Optional[str] = None
    opened_by: str = "system"
    auto_generated: bool = False


class DataQueryAnswer(BaseModel):
    """Request to answer a data query."""

    answered_by: str
    answer_text: str


class DataQueryClose(BaseModel):
    """Request to close a data query."""

    closed_by: str
    resolution_notes: Optional[str] = None


class DataQueryRequery(BaseModel):
    """Request to requery a previously answered data query."""

    requeried_by: str
    reason: str


class DataQueryUpdate(BaseModel):
    """Request to update query fields."""

    description: Optional[str] = None
    query_category: Optional[QueryCategory] = None
    expected_value: Optional[str] = None


class DataQueryListResponse(BaseModel):
    """Paginated list of data queries."""

    items: list[DataQuery]
    total: int
    limit: int
    offset: int


# ---------------------------------------------------------------------------
# Validation rules & results
# ---------------------------------------------------------------------------


class ValidationRule(BaseModel):
    """A validation rule for clinical data quality checks."""

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(..., description="Unique rule identifier")
    rule_name: str = Field(..., description="Human-readable rule name")
    rule_type: ValidationRuleType = Field(..., description="Type of validation")
    description: str = Field(..., description="Full rule description")
    expression: str = Field(..., description="Rule expression or logic")
    domain: str = Field(..., description="CDISC domain the rule applies to (e.g. DM, AE, LB)")
    fields: list[str] = Field(default_factory=list, description="Fields evaluated by this rule")
    severity: str = Field(default="ERROR", description="Severity: ERROR, WARNING, INFO")
    active: bool = Field(default=True, description="Whether the rule is active")
    auto_query: bool = Field(default=False, description="Whether failures auto-generate queries")
    created_at: datetime = Field(..., description="Rule creation timestamp")


class ValidationRuleCreate(BaseModel):
    """Request to create a validation rule."""

    rule_name: str
    rule_type: ValidationRuleType
    description: str
    expression: str
    domain: str
    fields: list[str] = Field(default_factory=list)
    severity: str = "ERROR"
    active: bool = True
    auto_query: bool = False


class ValidationRuleUpdate(BaseModel):
    """Request to update a validation rule."""

    rule_name: Optional[str] = None
    description: Optional[str] = None
    expression: Optional[str] = None
    severity: Optional[str] = None
    active: Optional[bool] = None
    auto_query: Optional[bool] = None


class ValidationResult(BaseModel):
    """Result of running a validation rule against data."""

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(..., description="Unique result identifier")
    rule_id: str = Field(..., description="Rule that produced this result")
    rule_name: str = Field(..., description="Name of the rule")
    trial_id: str = Field(..., description="Trial the data belongs to")
    patient_id: str = Field(..., description="Patient affected")
    field_name: str = Field(..., description="Field that was validated")
    current_value: Optional[str] = Field(None, description="Actual value found")
    expected_range: Optional[str] = Field(None, description="Expected range or format")
    passed: bool = Field(..., description="Whether the check passed")
    message: str = Field(..., description="Human-readable result message")
    checked_at: datetime = Field(..., description="Timestamp of check execution")


class ValidationResultListResponse(BaseModel):
    """Paginated list of validation results."""

    items: list[ValidationResult]
    total: int
    limit: int
    offset: int


class ValidationRuleListResponse(BaseModel):
    """Paginated list of validation rules."""

    items: list[ValidationRule]
    total: int


class BatchValidationRequest(BaseModel):
    """Request to run batch validation against a trial's data."""

    trial_id: str
    rule_ids: Optional[list[str]] = Field(None, description="Specific rule IDs; None = run all active rules")


class BatchValidationResponse(BaseModel):
    """Response from batch validation execution."""

    trial_id: str
    rules_executed: int
    total_checks: int
    passed: int
    failed: int
    results: list[ValidationResult]


# ---------------------------------------------------------------------------
# Clinical datasets & CDISC
# ---------------------------------------------------------------------------


class ClinicalDataset(BaseModel):
    """A CDISC-compliant clinical dataset with lifecycle management."""

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(..., description="Unique dataset identifier")
    trial_id: str = Field(..., description="Owning trial identifier")
    trial_name: str = Field(..., description="Human-readable trial name")
    name: str = Field(..., description="Dataset name (e.g. SDTM v1.0)")
    cdisc_standard: CDISCStandard = Field(..., description="CDISC standard")
    version: str = Field(..., description="Dataset version")
    status: DatasetStatus = Field(default=DatasetStatus.DRAFT, description="Current lifecycle status")
    lock_level: Optional[DataLockLevel] = Field(None, description="Current lock level")
    total_records: int = Field(default=0, description="Total records in dataset")
    total_variables: int = Field(default=0, description="Total variables across domains")
    completeness_percent: float = Field(default=0.0, description="Data completeness %")
    conformance_percent: float = Field(default=0.0, description="CDISC conformance %")
    created_at: datetime = Field(..., description="Creation timestamp")
    updated_at: datetime = Field(..., description="Last updated timestamp")
    frozen_at: Optional[datetime] = Field(None, description="When dataset was frozen")
    locked_at: Optional[datetime] = Field(None, description="When dataset was locked")
    locked_by: Optional[str] = Field(None, description="User who locked the dataset")
    release_notes: Optional[str] = Field(None, description="Release notes")


class ClinicalDatasetCreate(BaseModel):
    """Request to create a new clinical dataset."""

    trial_id: str
    trial_name: str
    name: str
    cdisc_standard: CDISCStandard
    version: str = "1.0"
    total_records: int = 0
    total_variables: int = 0


class ClinicalDatasetUpdate(BaseModel):
    """Request to update a clinical dataset."""

    name: Optional[str] = None
    version: Optional[str] = None
    total_records: Optional[int] = None
    total_variables: Optional[int] = None
    release_notes: Optional[str] = None


class DatasetFreezeRequest(BaseModel):
    """Request to freeze a clinical dataset."""

    frozen_by: str
    reason: Optional[str] = None


class DatasetLockRequest(BaseModel):
    """Request to lock a clinical dataset."""

    locked_by: str
    lock_level: DataLockLevel = DataLockLevel.SOFT_LOCK
    reason: Optional[str] = None


class DatasetReleaseRequest(BaseModel):
    """Request to release a clinical dataset."""

    released_by: str
    release_notes: str


class DatasetListResponse(BaseModel):
    """Paginated list of clinical datasets."""

    items: list[ClinicalDataset]
    total: int


class CDISCDomain(BaseModel):
    """A CDISC domain within a dataset (e.g. DM, AE, LB)."""

    model_config = ConfigDict(from_attributes=True)

    name: str = Field(..., description="Domain abbreviation (e.g. DM, AE, LB)")
    description: str = Field(..., description="Domain description")
    key_variables: list[str] = Field(default_factory=list, description="Key variables")
    required_variables: list[str] = Field(default_factory=list, description="Required variables")
    total_records: int = Field(default=0, description="Records in this domain")
    conformance_issues: int = Field(default=0, description="Conformance issues found")


class CDISCConformanceReport(BaseModel):
    """Report from running CDISC conformance checks."""

    dataset_id: str
    dataset_name: str
    standard: CDISCStandard
    domains_checked: int
    total_issues: int
    critical_issues: int
    warning_issues: int
    info_issues: int
    conformance_percent: float
    domain_results: list[CDISCDomainConformanceResult] = Field(default_factory=list)


class CDISCDomainConformanceResult(BaseModel):
    """Conformance result for a single CDISC domain."""

    domain: str
    total_checks: int
    passed: int
    failed: int
    issues: list[str] = Field(default_factory=list)


# Fix forward reference
CDISCConformanceReport.model_rebuild()


# ---------------------------------------------------------------------------
# Audit trail
# ---------------------------------------------------------------------------


class AuditTrailEntry(BaseModel):
    """An entry in the dataset audit trail."""

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(..., description="Unique audit entry identifier")
    dataset_id: str = Field(..., description="Dataset this audit entry belongs to")
    action: str = Field(..., description="Action performed (CREATE, UPDATE, FREEZE, LOCK, etc.)")
    field_name: Optional[str] = Field(None, description="Field that was changed")
    old_value: Optional[str] = Field(None, description="Previous value")
    new_value: Optional[str] = Field(None, description="New value")
    reason: Optional[str] = Field(None, description="Reason for the change")
    actor: str = Field(..., description="User who performed the action")
    timestamp: datetime = Field(..., description="When the action occurred")


class AuditTrailListResponse(BaseModel):
    """Paginated list of audit trail entries."""

    items: list[AuditTrailEntry]
    total: int


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------


class DataCleaningMetrics(BaseModel):
    """Aggregated data cleaning metrics for a trial."""

    trial_id: str
    trial_name: str
    total_queries: int = 0
    open_queries: int = 0
    answered_queries: int = 0
    closed_queries: int = 0
    cancelled_queries: int = 0
    requeried_queries: int = 0
    query_rate_per_page: float = Field(0.0, description="Queries per CRF page")
    auto_generated_percent: float = Field(0.0, description="% of queries auto-generated")
    queries_by_category: dict[str, int] = Field(default_factory=dict)
    validation_pass_rate: float = Field(0.0, description="% of validations that passed")
    total_validation_checks: int = 0
    failed_validation_checks: int = 0
    data_completeness_percent: float = 0.0


class QueryResolutionMetrics(BaseModel):
    """Metrics on query resolution performance."""

    trial_id: str
    avg_resolution_days: float = Field(0.0, description="Average days to resolve queries")
    median_resolution_days: float = Field(0.0, description="Median days to resolve queries")
    queries_resolved_within_7_days: int = 0
    queries_resolved_within_14_days: int = 0
    queries_resolved_after_14_days: int = 0
    total_resolved: int = 0
    requery_rate: float = Field(0.0, description="% of queries that were requeried")
    resolution_by_category: dict[str, float] = Field(default_factory=dict, description="Avg days by category")


class DatasetComparisonResult(BaseModel):
    """Result of comparing two dataset versions."""

    dataset_a_id: str
    dataset_a_name: str
    dataset_b_id: str
    dataset_b_name: str
    records_added: int = 0
    records_removed: int = 0
    records_modified: int = 0
    variables_added: int = 0
    variables_removed: int = 0
    completeness_delta: float = 0.0
    conformance_delta: float = 0.0
    summary: str = ""
