"""Pydantic schemas for Data Queries & Discrepancy Management (CLINICAL-18).

Manages clinical data query lifecycle: query generation and routing, response
tracking, auto-query rule engine, query aging reports, discrepancy resolution
workflow, and query metrics/analytics for CRO data management operations.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class QueryStatus(str, Enum):
    """Lifecycle status of a data query."""

    OPEN = "open"
    ANSWERED = "answered"
    CLOSED = "closed"
    CANCELLED = "cancelled"
    REQUERIED = "requeried"


class QueryPriority(str, Enum):
    """Priority level of a data query."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class QueryCategory(str, Enum):
    """Category classifying the type of data discrepancy."""

    MISSING_DATA = "missing_data"
    INCONSISTENT = "inconsistent"
    PROTOCOL_DEVIATION = "protocol_deviation"
    OUT_OF_RANGE = "out_of_range"
    CODING_ERROR = "coding_error"
    CONSENT = "consent"
    OTHER = "other"


class QuerySource(str, Enum):
    """Source that generated the data query."""

    MANUAL = "manual"
    AUTO_RULE = "auto_rule"
    SDV = "sdv"
    MEDICAL_REVIEW = "medical_review"


class ResolutionType(str, Enum):
    """Type of discrepancy resolution."""

    DATA_CORRECTED = "data_corrected"
    CONFIRMED_CORRECT = "confirmed_correct"
    SOURCE_VERIFIED = "source_verified"
    QUERY_WITHDRAWN = "query_withdrawn"
    NOT_APPLICABLE = "not_applicable"


# ---------------------------------------------------------------------------
# Core records
# ---------------------------------------------------------------------------


class QueryResponse(BaseModel):
    """A response to a data query from a site or reviewer."""

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(..., description="Unique response identifier")
    query_id: str = Field(..., description="Parent data query identifier")
    responder: str = Field(..., description="Name/role of the person responding")
    response_text: str = Field(..., description="Response text content")
    attachments: list[str] = Field(
        default_factory=list, description="List of attachment filenames"
    )
    created_at: datetime = Field(..., description="Response creation timestamp")


class DataQuery(BaseModel):
    """A data query record representing a discrepancy or question about clinical data."""

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(..., description="Unique data query identifier")
    trial_id: str = Field(..., description="Trial identifier")
    site_id: str = Field(..., description="Site identifier where query originates")
    subject_id: str | None = Field(None, description="Subject/patient identifier")
    visit_name: str | None = Field(None, description="Visit name or number")
    form_name: str = Field(..., description="CRF form name")
    field_name: str = Field(..., description="Field name within the form")
    query_text: str = Field(..., description="Query text describing the discrepancy")
    status: QueryStatus = Field(
        default=QueryStatus.OPEN, description="Current query lifecycle status"
    )
    priority: QueryPriority = Field(
        default=QueryPriority.MEDIUM, description="Query priority level"
    )
    category: QueryCategory = Field(..., description="Query category")
    source: QuerySource = Field(..., description="Source that generated the query")
    assigned_to: str | None = Field(None, description="Person/role assigned to resolve")
    auto_rule_id: str | None = Field(
        None, description="Auto-query rule ID if generated by rule engine"
    )
    responses: list[QueryResponse] = Field(
        default_factory=list, description="Responses to this query"
    )
    opened_date: datetime = Field(..., description="Date query was opened")
    answered_date: datetime | None = Field(None, description="Date query was answered")
    closed_date: datetime | None = Field(None, description="Date query was closed")
    created_at: datetime = Field(..., description="Record creation timestamp")


class AutoQueryRule(BaseModel):
    """An automatic query generation rule for programmatic data checks."""

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(..., description="Unique rule identifier")
    rule_name: str = Field(..., description="Human-readable rule name")
    condition: str = Field(
        ..., description="Condition expression (e.g., 'field IS NULL', 'value > ULN*3')"
    )
    form: str = Field(..., description="Target CRF form name")
    field: str = Field(..., description="Target field name")
    message_template: str = Field(
        ..., description="Query message template with placeholders"
    )
    category: QueryCategory = Field(
        default=QueryCategory.MISSING_DATA, description="Query category for generated queries"
    )
    priority: QueryPriority = Field(
        default=QueryPriority.MEDIUM, description="Default priority for generated queries"
    )
    active: bool = Field(default=True, description="Whether the rule is currently active")
    created_at: datetime = Field(..., description="Rule creation timestamp")


class DiscrepancyResolution(BaseModel):
    """Resolution details for a closed data query."""

    model_config = ConfigDict(from_attributes=True)

    query_id: str = Field(..., description="Data query identifier")
    resolution_type: ResolutionType = Field(..., description="Type of resolution applied")
    resolution_notes: str = Field(..., description="Notes describing the resolution")
    resolved_by: str = Field(..., description="Person who resolved the discrepancy")
    resolved_date: datetime = Field(..., description="Date of resolution")


# ---------------------------------------------------------------------------
# Request / response wrappers
# ---------------------------------------------------------------------------


class DataQueryCreate(BaseModel):
    """Request to create a new data query."""

    model_config = ConfigDict(from_attributes=True)

    trial_id: str = Field(..., description="Trial identifier")
    site_id: str = Field(..., description="Site identifier")
    subject_id: str | None = Field(None, description="Subject identifier")
    visit_name: str | None = Field(None, description="Visit name or number")
    form_name: str = Field(..., description="CRF form name")
    field_name: str = Field(..., description="Field name")
    query_text: str = Field(..., description="Query text")
    priority: QueryPriority = Field(
        default=QueryPriority.MEDIUM, description="Priority level"
    )
    category: QueryCategory = Field(..., description="Query category")
    source: QuerySource = Field(
        default=QuerySource.MANUAL, description="Query source"
    )
    assigned_to: str | None = Field(None, description="Assigned person/role")


class DataQueryUpdate(BaseModel):
    """Request to update a data query."""

    model_config = ConfigDict(from_attributes=True)

    query_text: str | None = Field(None, description="Updated query text")
    priority: QueryPriority | None = Field(None, description="Updated priority")
    category: QueryCategory | None = Field(None, description="Updated category")
    assigned_to: str | None = Field(None, description="Updated assignee")
    status: QueryStatus | None = Field(None, description="Updated status")


class QueryResponseCreate(BaseModel):
    """Request to add a response to a data query."""

    model_config = ConfigDict(from_attributes=True)

    responder: str = Field(..., description="Name/role of responder")
    response_text: str = Field(..., description="Response text")
    attachments: list[str] = Field(
        default_factory=list, description="Attachment filenames"
    )


class AutoQueryRuleCreate(BaseModel):
    """Request to create an auto-query rule."""

    model_config = ConfigDict(from_attributes=True)

    rule_name: str = Field(..., description="Rule name")
    condition: str = Field(..., description="Condition expression")
    form: str = Field(..., description="Target form")
    field: str = Field(..., description="Target field")
    message_template: str = Field(..., description="Message template")
    category: QueryCategory = Field(
        default=QueryCategory.MISSING_DATA, description="Query category"
    )
    priority: QueryPriority = Field(
        default=QueryPriority.MEDIUM, description="Default priority"
    )
    active: bool = Field(default=True, description="Whether rule is active")


class AutoQueryRuleUpdate(BaseModel):
    """Request to update an auto-query rule."""

    model_config = ConfigDict(from_attributes=True)

    rule_name: str | None = Field(None, description="Rule name")
    condition: str | None = Field(None, description="Condition expression")
    form: str | None = Field(None, description="Target form")
    field: str | None = Field(None, description="Target field")
    message_template: str | None = Field(None, description="Message template")
    category: QueryCategory | None = Field(None, description="Query category")
    priority: QueryPriority | None = Field(None, description="Default priority")
    active: bool | None = Field(None, description="Whether rule is active")


class QueryCloseRequest(BaseModel):
    """Request to close a data query with resolution details."""

    model_config = ConfigDict(from_attributes=True)

    resolution_type: ResolutionType = Field(..., description="Type of resolution")
    resolution_notes: str = Field(..., description="Resolution notes")
    resolved_by: str = Field(..., description="Person resolving")


class BulkCloseRequest(BaseModel):
    """Request to close multiple queries at once."""

    model_config = ConfigDict(from_attributes=True)

    query_ids: list[str] = Field(..., description="List of query IDs to close")
    resolution_type: ResolutionType = Field(..., description="Resolution type for all")
    resolution_notes: str = Field(..., description="Resolution notes")
    resolved_by: str = Field(..., description="Person resolving")


class BulkAssignRequest(BaseModel):
    """Request to assign multiple queries to a person."""

    model_config = ConfigDict(from_attributes=True)

    query_ids: list[str] = Field(..., description="List of query IDs to assign")
    assigned_to: str = Field(..., description="Person/role to assign queries to")


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------


class AgingBucket(BaseModel):
    """Query counts for a single aging time bucket."""

    model_config = ConfigDict(from_attributes=True)

    bucket: str = Field(..., description="Age bucket label (e.g., '0-7d')")
    count: int = Field(ge=0, description="Number of queries in this bucket")
    query_ids: list[str] = Field(
        default_factory=list, description="Query IDs in this bucket"
    )


class QueryAgingReport(BaseModel):
    """Report showing open queries grouped by age buckets."""

    model_config = ConfigDict(from_attributes=True)

    total_open: int = Field(ge=0, description="Total open queries")
    buckets: list[AgingBucket] = Field(
        default_factory=list, description="Aging buckets"
    )
    oldest_query_days: int = Field(
        ge=0, description="Age of the oldest open query in days"
    )
    generated_at: datetime = Field(..., description="Report generation timestamp")


class SiteQuerySummary(BaseModel):
    """Query summary for a single site."""

    model_config = ConfigDict(from_attributes=True)

    site_id: str = Field(..., description="Site identifier")
    total_queries: int = Field(ge=0, description="Total queries for this site")
    open_queries: int = Field(ge=0, description="Open queries")
    answered_queries: int = Field(ge=0, description="Answered queries")
    closed_queries: int = Field(ge=0, description="Closed queries")
    requeried_queries: int = Field(ge=0, description="Re-queried queries")
    avg_resolution_days: float = Field(
        ge=0.0, description="Average days to close queries"
    )


class QueryMetrics(BaseModel):
    """Aggregated data query metrics dashboard."""

    model_config = ConfigDict(from_attributes=True)

    total_queries: int = Field(ge=0, description="Total queries across all trials")
    open_queries: int = Field(ge=0, description="Currently open queries")
    answered_queries: int = Field(ge=0, description="Queries with responses pending review")
    closed_queries: int = Field(ge=0, description="Closed/resolved queries")
    cancelled_queries: int = Field(ge=0, description="Cancelled queries")
    requeried_queries: int = Field(ge=0, description="Re-queried queries")
    avg_resolution_days: float = Field(
        ge=0.0, description="Average days from open to close"
    )
    queries_by_category: dict[str, int] = Field(
        default_factory=dict, description="Query counts by category"
    )
    queries_by_site: dict[str, int] = Field(
        default_factory=dict, description="Query counts by site"
    )
    queries_by_priority: dict[str, int] = Field(
        default_factory=dict, description="Query counts by priority"
    )
    auto_query_count: int = Field(
        ge=0, description="Queries generated by auto-rules"
    )
    manual_query_count: int = Field(
        ge=0, description="Queries created manually"
    )


# ---------------------------------------------------------------------------
# List responses
# ---------------------------------------------------------------------------


class DataQueryListResponse(BaseModel):
    """List of data queries."""

    model_config = ConfigDict(from_attributes=True)

    items: list[DataQuery] = Field(default_factory=list)
    total: int = Field(ge=0, description="Total matching records")


class QueryResponseListResponse(BaseModel):
    """List of query responses."""

    model_config = ConfigDict(from_attributes=True)

    items: list[QueryResponse] = Field(default_factory=list)
    total: int = Field(ge=0, description="Total matching records")


class AutoQueryRuleListResponse(BaseModel):
    """List of auto-query rules."""

    model_config = ConfigDict(from_attributes=True)

    items: list[AutoQueryRule] = Field(default_factory=list)
    total: int = Field(ge=0, description="Total matching records")


class DiscrepancyResolutionListResponse(BaseModel):
    """List of discrepancy resolutions."""

    model_config = ConfigDict(from_attributes=True)

    items: list[DiscrepancyResolution] = Field(default_factory=list)
    total: int = Field(ge=0, description="Total matching records")


class SiteQuerySummaryListResponse(BaseModel):
    """List of site query summaries."""

    model_config = ConfigDict(from_attributes=True)

    items: list[SiteQuerySummary] = Field(default_factory=list)
    total: int = Field(ge=0, description="Total matching records")


class BulkOperationResult(BaseModel):
    """Result of a bulk operation."""

    model_config = ConfigDict(from_attributes=True)

    succeeded: list[str] = Field(
        default_factory=list, description="IDs that succeeded"
    )
    failed: list[str] = Field(
        default_factory=list, description="IDs that failed"
    )
    total_succeeded: int = Field(ge=0, description="Count of successful operations")
    total_failed: int = Field(ge=0, description="Count of failed operations")
