#!/bin/bash
# Generate a .env file with secure random credentials
# Run this once when setting up a new environment

set -e

if [ -f .env ]; then
    echo ".env already exists. Remove it first to regenerate."
    echo "  rm .env && bash scripts/generate_env.sh"
    exit 1
fi

echo "Generating .env with secure random credentials..."

cat > .env << 'TEMPLATE'
# Clinical Ontology Normalizer - Environment Configuration
# Generated by scripts/generate_env.sh
# IMPORTANT: Do not commit this file to git

# =============================================================================
# Database Credentials (auto-generated)
# =============================================================================
TEMPLATE

# Append generated values
echo "POSTGRES_USER=postgres" >> .env
echo "POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '\n')" >> .env
echo "POSTGRES_DB=clinical_ontology" >> .env
echo "" >> .env
echo "# Redis" >> .env
echo "REDIS_PASSWORD=$(openssl rand -base64 32 | tr -d '\n')" >> .env
echo "" >> .env
echo "# Neo4j" >> .env
echo "NEO4J_USER=neo4j" >> .env
echo "NEO4J_PASSWORD=$(openssl rand -base64 32 | tr -d '\n')" >> .env
echo "" >> .env
echo "# Authentication" >> .env
echo "API_KEY=$(openssl rand -hex 32)" >> .env
echo "JWT_SECRET_KEY=$(openssl rand -base64 64 | tr -d '\n')" >> .env
echo "AUTH_ENABLED=false" >> .env
echo "AUTH_BYPASS_DEV=true" >> .env
echo "" >> .env
echo "# Application" >> .env
echo "DEBUG=true" >> .env
echo "ENVIRONMENT=development" >> .env
echo "" >> .env
echo "# External API keys (set these manually if needed)" >> .env
echo "# ANTHROPIC_API_KEY=" >> .env
echo "# UMLS_API_KEY=" >> .env
echo "# METRIPORT_API_KEY=" >> .env
echo "# METRIPORT_WEBHOOK_KEY=" >> .env

echo ""
echo ".env generated with secure random credentials."
echo "Review the file and adjust settings as needed:"
echo "  cat .env"
